const KEY='osiris-econ-world-v1';
const CONCEPTS={micro:['supply_demand','elasticity','unit_economics','marginal_thinking','opportunity_cost','risk'],macro:['inflation','unemployment','monetary_policy','expectations','policy_lags','tradeoffs'],game:['incentives','cooperation','reciprocity','repeated_games','signaling','reputation']};
const LABEL={supply_demand:'Supply & Demand',elasticity:'Price Elasticity',unit_economics:'Unit Economics',marginal_thinking:'Marginal Thinking',opportunity_cost:'Opportunity Cost',risk:'Risk',inflation:'Inflation',unemployment:'Labor Tradeoffs',monetary_policy:'Monetary Policy',expectations:'Expectations',policy_lags:'Policy Lags',tradeoffs:'Policy Tradeoffs',incentives:'Incentives',cooperation:'Cooperation',reciprocity:'Reciprocity',repeated_games:'Repeated Games',signaling:'Signaling',reputation:'Reputation'};
const defaults=()=>({scores:{},discoveries:[],lastGame:null,lemon:{day:0,cash:20,last:null},bank:{q:0,inflation:3.4,unemployment:4.4,growth:2.1,rate:4.25,expectations:2.8,credibility:.72,stress:.15,last:null},dilemma:{round:0,you:0,them:0,trust:.5,reputation:.5,history:[],opponent:'mara',last:null}});
let state=(()=>{try{const raw=JSON.parse(localStorage.getItem(KEY)||'{}');return deepMerge(defaults(),raw)}catch{return defaults()}})();
function deepMerge(base,raw){for(const k of Object.keys(raw||{})){if(raw[k]&&typeof raw[k]==='object'&&!Array.isArray(raw[k])&&base[k]&&typeof base[k]==='object')base[k]=deepMerge(base[k],raw[k]);else base[k]=raw[k]}return base}
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const score=k=>Number(state.scores[k]||0); const learn=(k,e,lr=.22)=>{state.scores[k]=Math.max(0,Math.min(1,score(k)+lr*(e-score(k))))};
const avg=a=>a.reduce((s,k)=>s+score(k),0)/a.length; const money=n=>`$${Number(n).toFixed(2)}`; const pct=n=>`${Math.round(n*100)}%`; const $=id=>document.getElementById(id);
function goto(id){document.querySelectorAll('.screen').forEach(x=>x.classList.toggle('active',x.id===id));window.scrollTo({top:0,behavior:'smooth'});state.lastGame=id==='world'?state.lastGame:id;save();renderWorld()}
document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>goto(b.dataset.go));$('homeBtn').onclick=()=>goto('world');
function conceptDomain(k){if(CONCEPTS.micro.includes(k))return'micro';if(CONCEPTS.macro.includes(k))return'macro';return'game'}
function weakest(domain){return CONCEPTS[domain].slice().sort((a,b)=>score(a)-score(b))[0]}
function recommend(){let domains=[['micro',avg(CONCEPTS.micro)],['macro',avg(CONCEPTS.macro)],['game',avg(CONCEPTS.game)]].sort((a,b)=>a[1]-b[1]);let [d,v]=domains[0];if(state.lastGame&&gameId(d)===state.lastGame&&domains[1][1]-v<.1)[d,v]=domains[1];const c=weakest(d);return{domain:d,concept:c,game:gameId(d),urgency:v<.18?'HIGH':v<.4?'OPEN':'THREAD',title:d==='micro'?'Market Row':d==='macro'?'The Heights':'Low Harbor',reason:missionReason(d,c)}}
const gameId=d=>d==='micro'?'lemon':d==='macro'?'banker':'dilemma';
function missionReason(d,c){const l=LABEL[c];if(d==='micro')return`I keep seeing a blind spot around ${l.toLowerCase()}. Market Row can make that mistake expensive enough to remember.`;if(d==='macro')return`${l} is still fuzzy. The Heights will force you to separate what moves today from what moves months from now.`;return`${l} is the thread I want. Low Harbor is full of people who remember what you did, not what you meant.`}
function rank(){const a=[...CONCEPTS.micro,...CONCEPTS.macro,...CONCEPTS.game].reduce((s,k)=>s+score(k),0)/18;if(a>.72)return['Architect',5];if(a>.5)return['Strategist',4];if(a>.32)return['Operator',3];if(a>.15)return['Apprentice',2];return['Wanderer',1]}
function renderWorld(){const r=recommend(),[name,lv]=rank();$('rankBadge').textContent=`${name} · ${lv}`;$('missionTitle').textContent=r.title;$('missionUrgency').textContent=r.urgency;$('missionReason').textContent=r.reason;$('missionBtn').onclick=()=>goto(r.game);const learned=state.discoveries.length;if(!learned)$('worldOsiris').textContent='You can read economics in a book. Or you can walk into a world where it pushes back. I prefer the second way.';else $('worldOsiris').textContent=`You've uncovered ${learned} idea${learned===1?'':'s'}. I'm not interested in a perfect score. I'm interested in the pattern of mistakes you stop making.`;$('marketStatus').textContent=state.lemon.day?`Day ${state.lemon.day+1}. Cash: ${money(state.lemon.cash)}.`:'A cart waits under the old clocktower.';$('bankStatus').textContent=state.bank.q?`Quarter ${state.bank.q+1}. Credibility ${pct(state.bank.credibility)}.`:'The Republic is watching the next rate decision.';$('dockStatus').textContent=state.dilemma.round?`Encounter ${state.dilemma.round+1}. ${relationshipName()}.`:'Promises travel faster than ships here.';const sorted=[...CONCEPTS.micro,...CONCEPTS.macro,...CONCEPTS.game].sort((a,b)=>score(b)-score(a));$('strengthList').innerHTML=sorted.slice(0,3).map(k=>`<div class="note-item">${score(k)>.12?LABEL[k]:'Still gathering evidence'}</div>`).join('');$('gapList').innerHTML=sorted.slice(-3).reverse().map(k=>`<div class="note-item">${LABEL[k]} — ${gapPhrase(k)}</div>`).join('')}
function gapPhrase(k){if(score(k)<.12)return'untested';if(score(k)<.35)return'I want another experiment';return'getting clearer'}
$('toggleNotebook').onclick=()=>{const b=$('notebookBody');b.classList.toggle('hidden');$('toggleNotebook').textContent=b.classList.contains('hidden')?'open':'close'};

// ---------- MARKET ROW ----------
const marketEvents=[
 {title:'CLEAR SKIES OVER MARKET ROW',body:"Foot traffic is normal. Theo's cart is open across the square.",demand:1,cost:1,rival:1,mina:'“Theo charges three bucks across the street. He thinks tourists don’t look at prices. Prove him wrong.”'},
 {title:'HEAT WARNING ISSUED FOR MERIDIAN',body:'The city expects the hottest afternoon of the month. Tourists are already buying cold drinks before noon.',demand:1.28,cost:1,rival:1,mina:'“If there was ever a day people would pay for something cold, this is it.”'},
 {title:'THEO CUTS PRICES ACROSS THE SQUARE',body:'A hand-painted sign appears: LEMONADE — $1.50. Theo smiles when he sees you reading it.',demand:.82,cost:1,rival:.78,mina:'“He wants you to panic. The question is whether your customers care as much as he thinks.”'},
 {title:'LEMON SHORTAGE HITS WHOLESALERS',body:'Rosa texts before dawn: wholesale lemon prices jumped overnight. Your input cost is up 45%.',demand:1,cost:1.45,rival:1,mina:'“Same customers. More expensive lemons. Your old price may not mean the same thing anymore.”'},
 {title:'FOUNDERS FESTIVAL FILLS THE SQUARE',body:'Market Row is packed for the Founders Festival. A local food blogger mentions your cart.',demand:1.45,cost:1,rival:1.05,mina:'“You wanted attention. You have it. Don’t waste the crowd.”'}
];
function marketEvent(){return marketEvents[state.lemon.day%marketEvents.length]}
function renderLemon(){const e=marketEvent();$('lemonChapter').textContent=state.lemon.day+1;$('lemonSceneText').textContent=state.lemon.day===0?'The morning bell rings over Market Row. Your cart leans slightly left. You have $20, sixty paper cups, and exactly zero regular customers.':state.lemon.cash>80?'Market Row knows your name now. Theo has stopped laughing when you roll the cart into place.':'The old clocktower strikes eight. Yesterday is already gossip. Today is another market.';$('lemonHeadline').textContent=`THE MERIDIAN MORNING // ${e.title}`;$('lemonEvent').textContent=e.body;$('minaLine').textContent=e.mina;$('lemonGuide').textContent=lemonPrompt();$('lemonOutcome').classList.add('hidden');$('lemonDiscovery').classList.add('hidden');$('lemonDecision').classList.remove('hidden')}
function lemonPrompt(){const c=weakest('micro');if(c==='opportunity_cost')return'Every dollar you put into promotion is a dollar you cannot use somewhere else. Tell me what you are giving up.';if(c==='elasticity')return'Price is not just money. It is a test of how badly customers want what you sell.';if(c==='unit_economics')return'Revenue can look impressive while the business quietly loses money. Watch both sides.';return'Before we open: make a prediction. I care about whether your theory survives the street.'}
function runLemon(){const e=marketEvent(),price=Math.max(.25,+$('lemonPrice').value||2),units=Math.max(0,+$('lemonUnits').value||0),marketing=Math.max(0,+$('lemonMarketing').value||0),prediction=$('lemonPrediction').value,theory=$('lemonTheory').value.trim();const elasticity=1.25,demand=Math.max(0,Math.round(78*Math.pow(price/2,-elasticity)*e.demand*e.rival*(1+Math.log1p(marketing)*.035))),sold=Math.min(units,demand),unsold=units-sold,unitCost=.55*e.cost,revenue=sold*price,total=units*unitCost+2+marketing,profit=+(revenue-total).toFixed(2);state.lemon.day++;state.lemon.cash=+(state.lemon.cash+profit).toFixed(2);state.lemon.last={price,units,marketing,prediction,theory,demand,sold,unsold,profit,event:e};state.lastGame='lemon';save();$('lCash').textContent=money(state.lemon.cash);$('lSold').textContent=sold;$('lUnsold').textContent=unsold;$('lProfit').textContent=money(profit);let title,narrative,question,concept;if(unsold>Math.max(8,units*.25)){title='Crates remain under the awning.';narrative=`You made ${units} cups. ${sold} found buyers. Mina watches Theo pack up with less inventory than you.`;question=`You expected ${prediction==='sellout'?'a sellout':prediction==='balanced'?'most of the stock to move':'a surplus'}. What was different about how customers responded to your price?`;concept='elasticity'}else if(profit<0){title='Busy does not mean profitable.';narrative=`Customers handed you ${money(revenue)}, but the day cost ${money(total)}. The cash box is lighter than this morning.`;question='Which cost or decision mattered most? If sales rose but profit did not, what does that tell you?';concept='unit_economics'}else if(e.cost>1){title='The shortage gets into your margins.';narrative=`You sold ${sold} cups, but every cup cost more to make. Rosa was not exaggerating about the wholesale market.`;question='The customers did not create the shortage. Why did your best price change anyway?';concept='supply_demand'}else if(marketing>8&&profit>0){title='A line forms beneath your sign.';narrative=`The promotion pulled eyes toward the cart. The real question is whether the extra customers paid for the promotion itself.`;question='How would you decide whether one more dollar of promotion is worth spending tomorrow?';concept='marginal_thinking'}else{title='The till clicks shut with money inside.';narrative=`You sold ${sold} of ${units} cups and earned ${money(profit)} after costs. Theo pretends not to notice.`;question='If you changed only one thing tomorrow, which variable would teach you the most about why today worked?';concept='marginal_thinking'}state.lemon.last.concept=concept;$('lemonOutcomeTitle').textContent=title;$('lemonNarrative').textContent=narrative;$('lemonQuestion').textContent=question;$('lemonDecision').classList.add('hidden');$('lemonOutcome').classList.remove('hidden');renderWorld()}
$('runLemon').onclick=runLemon;
$('reflectLemon').onclick=()=>{const a=$('lemonReflection').value.trim();if(!a){$('lemonQuestion').textContent='Give me a theory first. Wrong is allowed; empty is not.';return}const c=state.lemon.last.concept,e=evidence(c,a);learn(c,e);if(state.lemon.last.theory)learn(c,Math.min(1,e+.08),.12);discover(c);$('lemonConcept').textContent=LABEL[c];$('lemonFeedback').textContent=feedback(c,e,a);$('lemonOutcome').classList.add('hidden');$('lemonDiscovery').classList.remove('hidden');save();renderWorld()};
$('nextLemon').onclick=()=>{ $('lemonTheory').value='';$('lemonReflection').value='';renderLemon() };

// ---------- THE HEIGHTS ----------
const bankEvents=[
 {h:'MARKETS WAIT FOR THE GOVERNOR',b:'Two-year yields are steady. Editorials warn against declaring victory too early.',inf:0,g:0,stress:0},
 {h:'ENERGY SHOCK HITS ASTER',b:'Fuel prices jump after a refinery outage. Households see the increase immediately.',inf:.55,g:-.18,stress:.04},
 {h:'BANKS TIGHTEN CREDIT',b:'Two regional lenders pull back from business loans. Markets begin whispering about recession.',inf:-.05,g:-.6,stress:.25},
 {h:'WAGE GROWTH SURPRISES',b:'Payroll growth remains strong and wages accelerate. Traders price a tougher inflation fight.',inf:.28,g:.35,stress:0},
 {h:'PRODUCTIVITY BOOM?',b:'New industrial automation data show output rising faster than hours worked.',inf:-.18,g:.65,stress:-.05}
];
function bankEvent(){return bankEvents[state.bank.q%bankEvents.length]}
function renderBank(){const e=bankEvent();$('bankQuarter').textContent=state.bank.q+1;$('bInflation').textContent=`${state.bank.inflation.toFixed(1)}%`;$('bUnemployment').textContent=`${state.bank.unemployment.toFixed(1)}%`;$('bGrowth').textContent=`${state.bank.growth.toFixed(1)}%`;$('bCredibility').textContent=pct(state.bank.credibility);$('bankRate').value=state.bank.rate;$('bankHeadline').textContent=`ASTER WIRE // ${e.h}`;$('bankBrief').textContent=e.b;$('lioLine').textContent=state.bank.credibility<.5?'“Governor, the problem is no longer just inflation. They are starting to doubt the reaction function itself.”':'“The staff can give you a forecast. We cannot give you certainty. Decide which risk you are willing to own.”';$('bankGuide').textContent=weakest('macro')==='expectations'?'The economy hears the rate. Markets hear the sentence around the rate. Those are different channels.':weakest('macro')==='policy_lags'?'Do not grade today’s policy using only today’s inflation. Ask what part of the economy has had time to react.':'You have two targets and one blunt instrument. Tell me the tradeoff you are choosing.';$('bankOutcome').classList.add('hidden');$('bankDiscovery').classList.add('hidden')}
function runBank(){const e=bankEvent(),s=state.bank,rate=Math.max(0,Math.min(20,+$('bankRate').value||s.rate)),guidance=$('bankGuidance').value,forecast=+$('bankForecast').value||s.inflation,theory=$('bankTheory').value.trim(),prediction=$('bankPrediction').value;const realPrior=s.rate-s.expectations,priorStance=realPrior-.75,newStance=(rate-s.expectations)-.75,guide=guidance==='hawkish'?-.18:guidance==='dovish'?.18:0;let expectations=.72*s.expectations+.28*s.inflation+guide;let growth=.58*s.growth+.42*2-.42*priorStance+e.g-.45*s.stress;let unemployment=.78*s.unemployment+.22*4.3+.28*(2-growth);let inflation=.62*s.inflation+.28*expectations+.2+.18*(s.growth-2)-.10*newStance+e.inf;let stress=Math.max(0,Math.min(1,.7*s.stress+.3*Math.max(0,rate-5)/5+e.stress));let credibility=s.credibility;const forecastError=Math.abs(forecast-inflation);credibility+=forecastError<.45?.05:forecastError>1?.-0.08:0;credibility+=(guidance==='hawkish'&&rate>=s.rate)||(guidance==='dovish'&&rate<=s.rate)?.025:-.015;credibility=Math.max(.1,Math.min(1,credibility));const expectedRate=s.rate+(guidance==='hawkish'?.35:guidance==='dovish'?-.35:0),surprise=rate-expectedRate,twoY=rate+.35*(expectations-2)+.45*surprise,equity=-1.6*surprise-1.1*e.stress+(.15*(growth-s.growth));state.bank={...s,q:s.q+1,inflation:+Math.max(0,inflation).toFixed(2),unemployment:+Math.max(0,unemployment).toFixed(2),growth:+growth.toFixed(2),rate:+rate.toFixed(2),expectations:+Math.max(0,expectations).toFixed(2),stress:+stress.toFixed(3),credibility:+credibility.toFixed(3),last:{prediction,theory,forecast,forecastError,twoY:+twoY.toFixed(2),equity:+equity.toFixed(2),event:e}};state.lastGame='banker';save();$('bYield').textContent=`${twoY.toFixed(2)}%`;$('bEquity').textContent=`${equity>=0?'+':''}${equity.toFixed(1)}%`;$('bAfterInflation').textContent=`${state.bank.inflation.toFixed(1)}%`;$('bAfterGrowth').textContent=`${state.bank.growth.toFixed(1)}%`;$('bankOutcomeTitle').textContent=Math.abs(surprise)>.4?'Markets lurch before the first loan resets.':'The statement lands. Traders start rewriting their forecasts.';$('bankNarrative').textContent=`Two-year yields move to ${twoY.toFixed(2)}%. Equities ${equity>=0?'rise':'fall'} ${Math.abs(equity).toFixed(1)}%. Inflation ends the quarter at ${state.bank.inflation.toFixed(1)}%, while growth prints ${state.bank.growth.toFixed(1)}%.`;$('bankQuestion').textContent=Math.abs(surprise)>.25?'Why did a market price move within minutes even though households and firms have barely had time to change behavior?':'Your forecast and the outcome are now both public. What happens to future policy if people stop believing your forecasts?';state.bank.last.concept=Math.abs(surprise)>.25?'policy_lags':'expectations';$('bankOutcome').classList.remove('hidden');renderWorld()}
$('runBank').onclick=runBank;
$('reflectBank').onclick=()=>{const a=$('bankReflection').value.trim();if(!a){$('bankQuestion').textContent='The cameras are still on. Give them an explanation.';return}const c=state.bank.last.concept,e=evidence(c,a);learn(c,e);learn('monetary_policy',Math.min(1,e+.08),.14);discover(c);$('bankConcept').textContent=LABEL[c];$('bankFeedback').textContent=feedback(c,e,a);$('bankOutcome').classList.add('hidden');$('bankDiscovery').classList.remove('hidden');save();renderWorld()};
$('nextBank').onclick=()=>{ $('bankTheory').value='';$('bankReflection').value='';renderBank() };

// ---------- LOW HARBOR ----------
const opponents={mara:{name:'Mara Voss',role:'Freight broker. Patient. Dangerous.',bio:'Mara built her business by remembering every favor and every betrayal.',strategy:'tft',intro:'“One container. Two manifests. If neither of us talks, we both make money. I can live with that.”'},cassian:{name:'Cassian Vale',role:'Importer. Charming. Opportunistic.',bio:'Cassian prefers the profitable move and assumes everyone else does too.',strategy:'greedy',intro:'“Trust is expensive. Luckily, betrayal can be profitable.”'},iona:{name:'Iona Reed',role:'Union negotiator. Tough. Forgiving.',bio:'Iona retaliates when pushed, but she leaves a door open for repair.',strategy:'forgiving',intro:'“I don’t need you to be nice. I need you to be predictable.”'},felix:{name:'Felix North',role:'Dockmaster. Quiet. Absolute.',bio:'Felix offers trust once. He does not offer it twice.',strategy:'grim',intro:'“You get one clean slate from me. Use it carefully.”'}};
function relationshipName(){const t=state.dilemma.trust;return t>.78?'Trusted partners':t>.6?'Working alliance':t>.38?'Uneasy partners':t>.2?'Damaged relationship':'Enemies'}
function renderDilemma(){const d=state.dilemma,o=opponents[d.opponent];$('dilemmaRound').textContent=d.round+1;$('oppName').textContent=o.name;$('oppRole').textContent=o.role;$('oppBio').textContent=o.bio;$('oppSpeaker').textContent=o.name.split(' ')[0];$('oppPortrait').textContent=o.name[0];$('oppDialogue').textContent=d.round===0?o.intro:d.trust>.7?'“We have a pattern now. I’d rather not break it.”':d.trust<.3?'“You’ve taught me not to take your word at face value.”':'“I’m still deciding whether today is about profit or precedent.”';$('relationshipLabel').textContent=relationshipName();$('trustText').textContent=d.trust>.65?'Trust is growing':d.trust<.35?'Trust is thin':'Trust is unresolved';$('dilemmaGuide').textContent=weakest('game')==='reputation'?'This person is not a payoff matrix. They carry your last move into the next room.':weakest('game')==='signaling'?'A promise changes expectations before either of you acts. That makes words strategic.':'One round rewards cleverness. Repeated rounds reward understanding the other mind.';$('dilemmaOutcome').classList.add('hidden');$('dilemmaDiscovery').classList.add('hidden')}
function oppAction(){const d=state.dilemma,o=opponents[d.opponent],h=d.history;if(!h.length)return'cooperate';const last=h[h.length-1].you;if(o.strategy==='tft')return last;if(o.strategy==='grim')return h.some(x=>x.you==='defect')?'defect':'cooperate';if(o.strategy==='forgiving')return h.slice(-2).every(x=>x.you==='defect')?'defect':'cooperate';if(o.strategy==='greedy')return d.trust>.72?'cooperate':'defect';return'cooperate'}
function playDilemma(you){const d=state.dilemma,o=opponents[d.opponent],promise=$('promise').value,pred=$('oppPrediction').value,theory=$('dilemmaTheory').value.trim(),them=oppAction(),pay={cooperate:{cooperate:[3,3],defect:[0,5]},defect:{cooperate:[5,0],defect:[1,1]}}[you][them],broken=promise!=='none'&&promise!==you;d.round++;d.you+=pay[0];d.them+=pay[1];if(you==='cooperate'&&them==='cooperate'){d.trust=Math.min(1,d.trust+.12);d.reputation=Math.min(1,d.reputation+.08)}else if(you==='defect'&&them==='cooperate'){d.trust=Math.max(0,d.trust-.28);d.reputation=Math.max(0,d.reputation-.22)}else if(you==='defect'&&them==='defect'){d.trust=Math.max(0,d.trust-.1);d.reputation=Math.max(0,d.reputation-.05)}else d.trust=Math.max(0,d.trust-.08);if(broken){d.trust=Math.max(0,d.trust-.16);d.reputation=Math.max(0,d.reputation-.18)}d.history.push({you,them,promise,pred,theory,broken});let c=broken?'signaling':you==='defect'&&them==='cooperate'?'reputation':you==='cooperate'&&them==='defect'?'reciprocity':'repeated_games';d.last={you,them,promise,pred,theory,broken,concept:c};state.lastGame='dilemma';save();$('dYou').textContent=d.you;$('dThem').textContent=d.them;$('dTrust').textContent=pct(d.trust);$('dRep').textContent=pct(d.reputation);let title,narrative,question;if(you==='defect'&&them==='cooperate'){title='You take the larger share. The room goes quiet.';narrative=`You gain 5. ${o.name} gains nothing. By sunset, three people in Low Harbor have heard how the deal ended.`;question='You maximized this round. What changed about the payoff of your next round?'}else if(you==='cooperate'&&them==='defect'){title=`${o.name} takes the opening.`;narrative='You honor the deal. They do not. The immediate payoff hurts, but now you have information about the person across from you.';question='Does being exploited once mean defection is now always optimal? What matters if the game continues?'}else if(you==='cooperate'){title='Both manifests clear the harbor.';narrative='Neither side grabs the maximum one-round payoff. Both leave with something more valuable than a single score: a pattern.';question='Why can two players rationally accept less today when they expect to meet again?'}else{title='Nobody trusts the room.';narrative='Both sides protect themselves. Both earn less than mutual cooperation would have produced.';question='If both of you expected betrayal, how did that expectation help create the bad outcome?'}if(broken)question='You said one thing and did another. Even if the move paid today, what did your promise change before the action happened?';$('dilemmaOutcomeTitle').textContent=title;$('dilemmaNarrative').textContent=narrative;$('dilemmaQuestion').textContent=question;$('dilemmaOutcome').classList.remove('hidden');renderWorld();renderDilemmaOutcomeOnly()}
function renderDilemmaOutcomeOnly(){/* preserve outcome visibility after character refresh */$('dilemmaOutcome').classList.remove('hidden')}
$('cooperate').onclick=()=>playDilemma('cooperate');$('defect').onclick=()=>playDilemma('defect');
$('reflectDilemma').onclick=()=>{const a=$('dilemmaReflection').value.trim();if(!a){$('dilemmaQuestion').textContent='Tell me what changed about the next encounter. That is the part I care about.';return}const c=state.dilemma.last.concept,e=evidence(c,a);learn(c,e);learn('repeated_games',Math.min(1,e+.06),.13);discover(c);$('dilemmaConcept').textContent=LABEL[c];$('dilemmaFeedback').textContent=feedback(c,e,a);$('dilemmaOutcome').classList.add('hidden');$('dilemmaDiscovery').classList.remove('hidden');save();renderWorld()};
$('nextDilemma').onclick=()=>{ $('dilemmaTheory').value='';$('dilemmaReflection').value='';renderDilemma() };

function evidence(c,a){const t=a.toLowerCase(),sets={elasticity:['price','demand','customers','sensitive','quantity','buy'],supply_demand:['supply','demand','cost','shortage','price'],unit_economics:['revenue','cost','profit','margin','expense'],marginal_thinking:['extra','next','incremental','additional','change'],opportunity_cost:['instead','give up','alternative','tradeoff'],policy_lags:['lag','time','later','months','quarter','slow'],expectations:['expect','believe','credibility','signal','forecast','anticipate'],monetary_policy:['rate','inflation','growth','unemployment','credit'],tradeoffs:['tradeoff','cost','inflation','jobs','growth'],reputation:['future','remember','trust','next','reputation'],reciprocity:['retaliate','forgive','respond','cooperate','defect'],repeated_games:['future','again','repeat','next','long run'],signaling:['promise','signal','expect','believe','word'],cooperation:['together','mutual','cooperate','both'],incentives:['payoff','reward','cost','benefit']};const hits=(sets[c]||[]).filter(k=>t.includes(k)).length;return Math.min(1,.25+hits*.16+Math.min(30,a.split(/\s+/).length)*.012)}
function feedback(c,e,a){if(e>.72)return`That explanation tracks the mechanism, not just the result. ${LABEL[c]} is now something you have used, not merely heard defined.`;if(e>.48)return`You're close. You identified part of the mechanism. On the next round, isolate one variable and see whether your explanation predicts the direction correctly.`;return`I’m not convinced yet—and that is useful. Keep the theory. We’ll put it in another situation and see if it survives.`}
function discover(c){if(!state.discoveries.includes(c))state.discoveries.push(c);save()}

renderWorld();renderLemon();renderBank();renderDilemma();
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
