import type { GameAction, GameState } from "@/lib/invisible-hands-v2/types";
import { globalActionGroups, globalAlerts, globalLegendItems, globalNodeCards, globalPreviewEffects, globalSupplyStress } from "@/lib/invisible-hands-v2/data";

type TurnPhase = "observe" | "preview" | "resolved";
type Resolution = { actionName: string; bullets: Array<{ text: string; tone: "positive" | "negative" | "neutral" }>; nextPressure: string; tags: string[]; affectedActors: string[]; affectedRoutes: string[] };

export function GlobalCommandLayout({ state, scenarioName, actions, selectedActions, turnPhase, onToggleAction, onAdvance, onNextTurn, onSetLayer, onRestart, children, resolution }: { state: GameState; scenarioName: string; actions: GameAction[]; selectedActions: GameAction[]; turnPhase: TurnPhase; onToggleAction: (id: string) => void; onAdvance: () => void; onNextTurn: () => void; onSetLayer: (layer: "micro" | "macro" | "global") => void; onRestart: () => void; children: React.ReactNode; resolution?: Resolution }) {
  const previews = selectedActions.map((action) => globalPreviewEffects.find((preview) => preview.actionId === action.id)).filter(Boolean);
  const selectedNode = globalNodeCards.find((node) => node.actorId === (state.selectedActorId ?? "global-domestic")) ?? globalNodeCards[0];
  const statValue = (key: string) => (state[key as keyof GameState] as number | undefined)?.toFixed?.(0);
  const selectedIds = new Set(selectedActions.map((action) => action.id));
  const previewDeltas = previews.flatMap((preview) => preview?.expectedDeltas ?? []);

  return <section className="min-h-screen bg-[#071120] p-3 text-[#d9eeff]"><div className="mx-auto max-w-[1800px] rounded-xl border border-cyan-400/30 bg-[#0a1b32] p-2 shadow-[0_0_50px_rgba(34,211,238,.15)_inset]">
    <header className="mb-2 grid gap-2 text-xs xl:grid-cols-[260px_repeat(7,minmax(0,1fr))]">
      <div className="rounded border border-cyan-300/35 bg-[#0b2747] p-2"><p className="text-xl font-bold tracking-wider">INVISIBLE HANDS</p><p className="text-[10px] text-cyan-200">GLOBAL COMMAND</p></div>
      {[["Scenario",scenarioName],["Turn",`${String(state.turn).padStart(3,"0")}`],["Stability",`${state.stabilityScore.toFixed(0)}%`],["Inflation",`${state.inflation.toFixed(1)}%`],["Trade",`$${state.tradeBalance.toFixed(0)}B`],["FX",`${state.currencyStrength.toFixed(0)}`],["Confidence",`${state.publicConfidence.toFixed(0)}`]].map(([key,value])=><div key={key} className="rounded border border-cyan-300/30 bg-[#102844] p-2"><p className="text-[10px] uppercase text-cyan-200/80">{key}</p><p className="mt-1 text-lg font-semibold">{value}</p></div>)}
    </header>
    <div className="mb-2 flex flex-wrap gap-2">{(["micro","macro","global"] as const).map((layer)=><button key={layer} onClick={()=>onSetLayer(layer)} className={`rounded border px-3 py-1 text-xs font-semibold uppercase ${state.layer===layer?"border-cyan-200 bg-cyan-300/15 text-cyan-50":"border-slate-600 text-slate-300"}`}>{layer}</button>)}<button onClick={onRestart} className="ml-auto rounded border border-amber-300/40 px-3 py-1 text-xs font-semibold text-amber-100">Restart scenario</button></div>
    <div className="grid gap-2 xl:grid-cols-[260px_1fr_320px]">
      <aside className="space-y-2 text-xs">{[["Global Overview",[`Trade climate: ELEVATED FRICTION`,`Volatility: ${state.marketVolatility.toFixed(0)} / 100`,`Supply stress: ${state.supplyStress.toFixed(0)} / 100`,`Policy window: NARROW`]],["Trade Flow Legend",globalLegendItems],["Supply Chain Stress",globalSupplyStress.map(item=>`${item.name} ${item.level}`)],["Active Alerts",globalAlerts]].map(([title,rows])=><div key={title as string} className="rounded border border-cyan-300/30 bg-[#0e2440] p-3"><p className="mb-2 font-semibold uppercase text-cyan-100">{title as string}</p><div className="space-y-1 text-cyan-50/90">{(rows as string[]).map(row=><p key={row}>{row}</p>)}</div></div>)}</aside>
      {children}
      <aside className="space-y-2 text-xs">
        <button onClick={turnPhase==="resolved"?onNextTurn:onAdvance} disabled={Boolean(state.endState)} className={`w-full rounded border px-3 py-3 text-base font-bold tracking-wide disabled:cursor-not-allowed disabled:opacity-50 ${turnPhase==="preview"?"border-amber-300 bg-amber-300/15 text-amber-100 shadow-[0_0_22px_rgba(251,191,36,.35)]":"border-cyan-300/40 bg-[#0f2b4a]"}`}>{state.endState?"CAMPAIGN COMPLETE":turnPhase==="resolved"?"NEXT TURN":"ADVANCE TURN"}</button>
        <div className="rounded border border-cyan-300/30 bg-[#0e2440] p-3"><p className="font-semibold uppercase text-cyan-100">Selected Actor</p><p className="mt-2 text-sm font-bold">{selectedNode.title}</p><p className="text-cyan-100/70">{selectedNode.subtitle} · {selectedNode.status}</p><div className="mt-2 space-y-1">{selectedNode.rows.map((row)=><p key={row.label}>{row.label}: {row.value.startsWith("STATE:") ? `${statValue(row.value.replace("STATE:",""))}` : row.value}</p>)}</div></div>
        {turnPhase!=="resolved"?<div className="rounded border border-cyan-300/30 bg-[#0e2440] p-3"><div className="mb-2 flex items-center justify-between"><p className="font-semibold uppercase text-cyan-100">Command Actions</p><span className="text-[10px] text-amber-200">{selectedActions.length}/2 selected</span></div><div className="space-y-2">{globalActionGroups.map((group)=><div key={group.title}><p className="text-[10px] uppercase text-cyan-200/80">{group.title}</p><div className="mt-1 grid grid-cols-1 gap-1">{group.actionIds.map((id)=>actions.find((action)=>action.id===id)).filter(Boolean).map((action)=><button key={action!.id} onClick={()=>onToggleAction(action!.id)} className={`w-full rounded border px-2 py-2 text-left ${selectedIds.has(action!.id)?"border-amber-300 bg-amber-400/15":"border-cyan-300/30 bg-[#123154]"}`}><span className="font-semibold">{action!.name}</span><span className="mt-1 block text-[10px] text-cyan-100/65">{action!.downside}</span></button>)}</div></div>)}</div></div>:null}
        {selectedActions.length?<div className="rounded border border-amber-300/40 bg-[#2b2516] p-3"><p className="font-semibold uppercase text-amber-200">Policy package preview</p><p className="mt-1 text-sm font-bold">{selectedActions.map(action=>action.name).join(" + ")}</p><div className="mt-2 space-y-1">{previewDeltas.slice(0,8).map((delta,index)=><p key={`${delta.label}-${index}`}>{delta.label}: {delta.value}</p>)}</div><p className="mt-2 text-[10px] text-amber-100/70">Combining policies can activate second-order interactions in the simulation.</p></div>:null}
        {turnPhase==="resolved" && resolution ? <div className="rounded border border-cyan-300/30 bg-[#0e2440] p-3"><p className="font-semibold uppercase text-cyan-100">Turn Report</p><p className="mt-1 text-sm font-bold">Package enacted: {resolution.actionName}</p><ul className="mt-2 list-disc space-y-1 pl-4">{resolution.bullets.map((bullet)=><li key={bullet.text}>{bullet.text}</li>)}</ul><p className="mt-2">Affected actors: {resolution.affectedActors.join(", ") || "None"}</p><p>Affected routes: {resolution.affectedRoutes.join(", ") || "None"}</p><p className="mt-2 text-amber-200">Next pressure: {resolution.nextPressure}</p></div> : null}
      </aside>
    </div>
  </div></section>;
}
