import type { ScenarioEvent } from "./types";

export const invisibleHandsEvents: ScenarioEvent[] = [
  {
    id: "import_surge",
    turn: 1,
    title: "Eastport steel lands below domestic cost",
    description: "Port Meridian mills announce layoffs after Eastport exporters undercut domestic prices. The steel lobby demands immediate border protection.",
    availablePolicyActionIds: ["no_action", "steel_tariff_10", "steel_tariff_25", "negotiate_with_eastport", "worker_adjustment_aid"],
    affectedAgents: ["Steel Lobby", "Auto Sector", "Consumers / Voters", "Eastport"],
    frameworkTags: ["Specific Factors", "Tariff Welfare Analysis"],
    educationalNote: "Trade creates broad gains but concentrated losses. Specific factors such as mill equipment and local skills cannot instantly move to expanding sectors.",
  },
  {
    id: "auto_warning",
    turn: 2,
    title: "Auto firms warn of input-cost shock",
    description: "Auto executives say steel protection could turn into assembly-line layoffs if input costs rise faster than contracts allow.",
    availablePolicyActionIds: ["auto_supply_chain_support", "steel_tariff_10", "reduce_trade_barriers", "local_content_requirement", "hold_rate"],
    affectedAgents: ["Auto Sector", "Markets", "Consumers / Voters"],
    frameworkTags: ["Supply Chain Frictions", "Specific Factors"],
    educationalNote: "A tariff on an upstream input can protect one sector while taxing downstream producers that compete globally.",
  },
  {
    id: "eastport_signal",
    turn: 3,
    title: "Eastport floats retaliation list",
    description: "Eastport publishes a draft retaliation list led by Port Meridian wheat, apples, and auto components.",
    availablePolicyActionIds: ["negotiate_with_eastport", "export_promotion", "steel_import_quota", "steel_tariff_25", "no_action"],
    affectedAgents: ["Eastport", "Agriculture", "Auto Sector", "Markets"],
    frameworkTags: ["Repeated Prisoner’s Dilemma", "Credible Threats"],
    educationalNote: "Retaliation threats can be bargaining tools, but repeated interaction makes reputation and future cooperation valuable.",
  },
  {
    id: "inflation_print",
    turn: 4,
    title: "Inflation expectations drift higher",
    description: "Households and bond traders start asking whether tariff pass-through will become a broader inflation problem.",
    availablePolicyActionIds: ["hike_rate", "hawkish_guidance", "consumer_rebate", "hold_rate", "cut_rate"],
    affectedAgents: ["Central Bank", "Markets", "Consumers / Voters"],
    frameworkTags: ["Central Bank Signaling", "Market Expectations"],
    educationalNote: "Expected inflation matters because price setters and wage bargainers update behavior before official inflation fully appears.",
  },
  {
    id: "mill_modernization",
    turn: 5,
    title: "Steel firms request modernization support",
    description: "Mill owners admit some competitiveness problems are old equipment and energy inefficiency rather than imports alone.",
    availablePolicyActionIds: ["steel_modernization_subsidy", "worker_adjustment_aid", "infrastructure_investment", "steel_tariff_10", "austerity_package"],
    affectedAgents: ["Steel Lobby", "Markets", "Consumers / Voters"],
    frameworkTags: ["Specific Factors", "Market Expectations"],
    educationalNote: "Protection changes prices immediately; productivity policy changes capabilities slowly and depends on credible execution.",
  },
  {
    id: "bond_vigilantes",
    turn: 6,
    title: "Bond desks question fiscal capacity",
    description: "After several relief proposals, analysts ask whether Port Meridian can fund industrial policy without weakening debt sustainability.",
    availablePolicyActionIds: ["austerity_package", "infrastructure_investment", "hold_rate", "hawkish_guidance", "consumer_rebate"],
    affectedAgents: ["Markets", "Central Bank", "Consumers / Voters"],
    frameworkTags: ["Market Expectations", "Bayesian Updating"],
    educationalNote: "Markets update beliefs from policy sequences, not isolated announcements. Debt can finance capacity or signal political drift.",
  },
  {
    id: "bank_funding",
    turn: 7,
    title: "Regional banks report credit stress",
    description: "Suppliers caught between higher steel costs and slower orders draw credit lines, raising bank funding pressure.",
    availablePolicyActionIds: ["emergency_liquidity", "cut_rate", "hike_rate", "auto_supply_chain_support", "hold_rate"],
    affectedAgents: ["Banking", "Markets", "Central Bank"],
    frameworkTags: ["Central Bank Signaling", "Supply Chain Frictions"],
    educationalNote: "A real-economy shock can become financial stress when firms rely on short-term credit to bridge disrupted cash flow.",
  },
  {
    id: "voter_backlash",
    turn: 8,
    title: "Voters split over prices versus jobs",
    description: "Steel towns praise job protection while urban households blame policy for higher car and appliance prices.",
    availablePolicyActionIds: ["consumer_rebate", "worker_adjustment_aid", "reduce_trade_barriers", "steel_tariff_10", "dovish_guidance"],
    affectedAgents: ["Consumers / Voters", "Steel Lobby", "Auto Sector"],
    frameworkTags: ["Political Economy", "Tariff Welfare Analysis"],
    educationalNote: "Democratic pressure aggregates unevenly: concentrated beneficiaries can organize while diffuse consumers react through approval and elections.",
  },
  {
    id: "supply_chain_snarl",
    turn: 9,
    title: "Supply-chain bottlenecks hit exporters",
    description: "Port congestion and steel sourcing rules delay auto parts and refrigerated agriculture shipments.",
    availablePolicyActionIds: ["infrastructure_investment", "reduce_trade_barriers", "auto_supply_chain_support", "local_content_requirement", "export_promotion"],
    affectedAgents: ["Auto Sector", "Agriculture", "Markets"],
    frameworkTags: ["Supply Chain Frictions", "Gravity Model"],
    educationalNote: "Trade volume responds not only to tariffs but also distance, logistics, standards, reliability, and administrative friction.",
  },
  {
    id: "credibility_test",
    turn: 10,
    title: "Central bank credibility faces a public test",
    description: "Commentators compare the bank's guidance with the government's fiscal and trade stance. Inflation expectations hang in the balance.",
    availablePolicyActionIds: ["hawkish_guidance", "hike_rate", "hold_rate", "cut_rate", "dovish_guidance"],
    affectedAgents: ["Central Bank", "Markets", "Consumers / Voters"],
    frameworkTags: ["Central Bank Signaling", "Bayesian Updating"],
    educationalNote: "Credibility is a stock built through consistency. Contradictory actions make every future announcement less powerful.",
  },
  {
    id: "trade_truce_window",
    turn: 11,
    title: "Eastport offers a narrow truce window",
    description: "Eastport will discuss export monitoring and standards cooperation if Port Meridian avoids a final escalation.",
    availablePolicyActionIds: ["negotiate_with_eastport", "reduce_trade_barriers", "export_promotion", "steel_tariff_25", "steel_import_quota"],
    affectedAgents: ["Eastport", "Agriculture", "Steel Lobby", "Markets"],
    frameworkTags: ["Repeated Prisoner’s Dilemma", "Credible Threats"],
    educationalNote: "Late-game cooperation may recover future gains, but domestic groups may interpret compromise as weakness.",
  },
  {
    id: "final_budget",
    turn: 12,
    title: "Final emergency budget before elections",
    description: "The cabinet has one final move to stabilize welfare, credibility, or political survival before voters and markets render judgment.",
    availablePolicyActionIds: ["worker_adjustment_aid", "steel_modernization_subsidy", "austerity_package", "consumer_rebate", "hold_rate", "negotiate_with_eastport"],
    affectedAgents: ["Consumers / Voters", "Markets", "Steel Lobby", "Central Bank"],
    frameworkTags: ["Political Economy", "Market Expectations"],
    educationalNote: "Endgame policy reveals priorities. Stabilization often means choosing which constraint binds least dangerously.",
  },
];

export function getEventForTurn(turn: number): ScenarioEvent {
  return invisibleHandsEvents[Math.min(Math.max(turn, 1), invisibleHandsEvents.length) - 1];
}
