import type { GameState } from "./types";

export const invisibleHandsInitialState: GameState = {
  economy: {
    turn: 1,
    maxTurns: 12,
    gdpGrowth: 2.0,
    inflation: 3.5,
    inflationExpectations: 3.2,
    unemployment: 5.2,
    debtToGdp: 72,
    fiscalBalance: -3.5,
    approval: 55,
    welfare: 100,
    crisisRisk: 20,
    centralBankCredibility: 70,
    marketConfidence: 65,
    currencyIndex: 100,
    bondYield: 4.2,
    equityIndex: 100,
    bankStress: 20,
    retaliationRisk: 15,
    tariffLevel: 0,
    tradeBalance: -2.5,
    supplyChainStress: 25,
    eastportRelationship: 60,
    policyRate: 4.5,
    commodityPressure: 35,
    exportAccess: 82,
  },
  sectors: {
    steel: {
      output: 100,
      jobs: 42000,
      productivity: 45,
      lobbyPower: 85,
      importExposure: 70,
      pricePressure: 30,
      stress: 65,
      politicalSalience: 80,
    },
    autos: {
      output: 100,
      jobs: 90000,
      productivity: 65,
      exportDependence: 60,
      inputCostExposure: 75,
      stress: 30,
      lobbyPower: 60,
    },
    agriculture: {
      output: 100,
      jobs: 65000,
      productivity: 55,
      exportDependence: 80,
      retaliationExposure: 85,
      stress: 25,
    },
    consumerGoods: {
      output: 100,
      importExposure: 75,
      priceSensitivity: 90,
      stress: 30,
    },
    banking: {
      output: 100,
      creditGrowth: 4,
      stress: 20,
      defaultRisk: 15,
    },
  },
  delayedEffects: [],
  actionHistory: [],
  frameworksEncountered: [],
  bestDecisions: [],
  worstDecisions: [],
  log: [],
};
