import type { PolicyAction } from "./types";

export const invisibleHandsPolicies: PolicyAction[] = [
  {
    id: "no_action",
    label: "No action",
    category: "Trade",
    description: "Keep policy unchanged while watching market and sector reactions.",
    immediateEffects: { economy: { approval: -2, crisisRisk: 2 }, sectors: { steel: { stress: 5 } } },
    delayedEffects: [{ id: "import_pressure_continues", label: "Import pressure continues", delay: 1, sectors: { steel: { output: -2, stress: 3 } }, economy: { unemployment: 0.1 } }],
    frameworkTags: ["Political Economy", "Bayesian Updating"],
    advisorHint: { easy: "Low inflation risk, but steel workers and lobbyists will punish visible inaction.", normal: "Waiting preserves optionality, but concentrated losses can become politically loud.", hard: "Status quo." },
  },
  {
    id: "steel_tariff_10",
    label: "Impose 10% steel tariff",
    category: "Trade",
    description: "Add moderate import protection for domestic steel producers.",
    immediateEffects: { economy: { tariffLevel: 10, inflation: 0.25, approval: 2, retaliationRisk: 7, eastportRelationship: -6, supplyChainStress: 4 }, sectors: { steel: { output: 5, jobs: 1200, stress: -10 }, autos: { stress: 5 }, consumerGoods: { stress: 3, pricePressure: 4 } } },
    delayedEffects: [{ id: "tariff_cost_pass_through", label: "Tariff cost pass-through", delay: 2, economy: { inflationExpectations: 0.2, welfare: -2 }, sectors: { autos: { output: -2, stress: 3 } } }],
    frameworkTags: ["Tariff Welfare Analysis", "Specific Factors"],
    advisorHint: { easy: "Helps steel quickly, but raises prices and retaliation risk.", normal: "A moderate tariff buys time while pushing costs into steel-using sectors.", hard: "Protection with pass-through." },
  },
  {
    id: "steel_tariff_25",
    label: "Impose 25% steel tariff",
    category: "Trade",
    description: "Use aggressive protection to force a rapid shift toward domestic steel.",
    immediateEffects: { economy: { tariffLevel: 25, inflation: 0.7, approval: 3, retaliationRisk: 18, eastportRelationship: -15, supplyChainStress: 11, crisisRisk: 4 }, sectors: { steel: { output: 11, jobs: 3200, stress: -18 }, autos: { output: -4, stress: 12 }, agriculture: { stress: 5 }, consumerGoods: { stress: 8, pricePressure: 8 } } },
    delayedEffects: [{ id: "retaliation_watch", label: "Retaliation watch", delay: 1, economy: { retaliationRisk: 8, marketConfidence: -3 }, sectors: { agriculture: { stress: 8 }, autos: { stress: 5 } } }],
    frameworkTags: ["Tariff Welfare Analysis", "Credible Threats", "Political Economy"],
    advisorHint: { easy: "Big steel boost, but likely inflation, angry exporters, and Eastport retaliation.", normal: "A credible threat can become a costly repeated-game signal.", hard: "Large wedge." },
  },
  {
    id: "steel_import_quota",
    label: "Impose steel quota",
    category: "Trade",
    description: "Cap import volumes instead of taxing each imported unit.",
    immediateEffects: { economy: { tariffLevel: 18, inflation: 0.45, retaliationRisk: 13, eastportRelationship: -12, supplyChainStress: 14 }, sectors: { steel: { output: 8, jobs: 2200, stress: -14 }, autos: { output: -5, stress: 14 }, consumerGoods: { stress: 6 } } },
    delayedEffects: [{ id: "quota_rents", label: "Quota rents and shortages", delay: 2, economy: { welfare: -4, inflation: 0.2 }, sectors: { autos: { stress: 4 }, consumerGoods: { stress: 4 } } }],
    frameworkTags: ["Tariff Welfare Analysis", "Supply Chain Frictions"],
    advisorHint: { easy: "Quotas protect steel but can create shortages and hidden quota rents.", normal: "Volume caps are blunt when supply chains need reliable inputs.", hard: "Quantity constraint." },
  },
  {
    id: "negotiate_with_eastport",
    label: "Negotiate with Eastport",
    category: "Trade",
    description: "Open talks on import surges, monitoring, and voluntary adjustment.",
    immediateEffects: { economy: { eastportRelationship: 10, retaliationRisk: -8, marketConfidence: 3, approval: 1, crisisRisk: -2 } },
    delayedEffects: [{ id: "trade_truce", label: "Trade truce confidence", delay: 2, economy: { exportAccess: 4, tradeBalance: 0.3, supplyChainStress: -4 }, sectors: { agriculture: { stress: -4 }, autos: { stress: -3 } } }],
    frameworkTags: ["Repeated Prisoner’s Dilemma", "Credible Threats"],
    advisorHint: { easy: "Improves relations and lowers retaliation risk, but does not immediately rescue steel.", normal: "Cooperation can preserve future payoffs if domestic politics tolerate delay.", hard: "Repeated-game play." },
  },
  {
    id: "reduce_trade_barriers",
    label: "Reduce trade barriers",
    category: "Trade",
    description: "Signal openness by cutting administrative barriers and import frictions.",
    immediateEffects: { economy: { tariffLevel: -10, inflation: -0.25, eastportRelationship: 8, retaliationRisk: -6, welfare: 3 }, sectors: { steel: { stress: 10, output: -4 }, autos: { stress: -5, output: 3 }, consumerGoods: { stress: -5 } } },
    delayedEffects: [{ id: "consumer_real_income", label: "Consumer real income improves", delay: 1, economy: { approval: 2, inflationExpectations: -0.1 } }],
    frameworkTags: ["Gravity Model", "Specific Factors"],
    advisorHint: { easy: "Good for consumers and input users, painful for steel communities.", normal: "Diffuse gains may not offset concentrated political losses.", hard: "Liberalization." },
  },
  {
    id: "export_promotion",
    label: "Export promotion",
    category: "Trade",
    description: "Fund trade finance and market access support for exporters.",
    immediateEffects: { economy: { fiscalBalance: -0.2, debtToGdp: 0.4, tradeBalance: 0.4, approval: 1 }, sectors: { agriculture: { output: 3, stress: -4 }, autos: { output: 2, stress: -2 } } },
    delayedEffects: [{ id: "export_pipeline", label: "Export pipeline matures", delay: 2, economy: { gdpGrowth: 0.2, exportAccess: 3, welfare: 2 } }],
    frameworkTags: ["Gravity Model", "Political Economy"],
    advisorHint: { easy: "Supports agriculture and autos, with modest debt cost.", normal: "Helps exposed exporters without directly resolving steel imports.", hard: "Export push." },
  },
  {
    id: "local_content_requirement",
    label: "Local content requirement",
    category: "Trade",
    description: "Require key manufacturers to source a share of steel domestically.",
    immediateEffects: { economy: { inflation: 0.35, supplyChainStress: 12, eastportRelationship: -8, retaliationRisk: 9 }, sectors: { steel: { output: 7, stress: -9 }, autos: { output: -6, stress: 16 }, consumerGoods: { stress: 4 } } },
    delayedEffects: [{ id: "compliance_drag", label: "Compliance drag", delay: 1, economy: { gdpGrowth: -0.2, welfare: -2 }, sectors: { autos: { stress: 5 } } }],
    frameworkTags: ["Supply Chain Frictions", "Specific Factors"],
    advisorHint: { easy: "Protects steel but hurts auto competitiveness and supply-chain flexibility.", normal: "Industrial targeting can become an input tax on downstream firms.", hard: "Domestic sourcing mandate." },
  },
  {
    id: "worker_adjustment_aid",
    label: "Worker adjustment aid",
    category: "Fiscal / Industrial",
    description: "Provide wage insurance, retraining, and relocation support for displaced steel workers.",
    immediateEffects: { economy: { fiscalBalance: -0.4, debtToGdp: 0.6, approval: 2, welfare: 2 }, sectors: { steel: { stress: -4 } } },
    delayedEffects: [{ id: "retraining_effect", label: "Retraining lowers unemployment pressure", delay: 2, economy: { unemployment: -0.25, welfare: 3, approval: 2 }, sectors: { steel: { stress: -4 } } }],
    frameworkTags: ["Specific Factors", "Political Economy"],
    advisorHint: { easy: "Reduces unemployment pressure later but raises debt now.", normal: "Compensation can make adjustment politically feasible.", hard: "Compensate losers." },
  },
  {
    id: "steel_modernization_subsidy",
    label: "Steel modernization subsidy",
    category: "Fiscal / Industrial",
    description: "Finance productivity upgrades for mills rather than pure protection.",
    immediateEffects: { economy: { fiscalBalance: -0.7, debtToGdp: 1.1, approval: 2 }, sectors: { steel: { stress: -7, productivity: 3, lobbyPower: 2 } } },
    delayedEffects: [{ id: "modernized_mills", label: "Modernized mills lift productivity", delay: 3, economy: { gdpGrowth: 0.25, welfare: 3 }, sectors: { steel: { output: 7, productivity: 7, stress: -8 } } }],
    frameworkTags: ["Specific Factors", "Market Expectations"],
    advisorHint: { easy: "Costs money now, but improves steel productivity later.", normal: "Better than permanent protection if upgrades actually arrive before politics turns.", hard: "Capex bet." },
  },
  {
    id: "auto_supply_chain_support",
    label: "Auto supply-chain support",
    category: "Fiscal / Industrial",
    description: "Offer temporary credit and logistics support to steel-using manufacturers.",
    immediateEffects: { economy: { fiscalBalance: -0.3, debtToGdp: 0.4, gdpGrowth: 0.1 }, sectors: { autos: { stress: -8, output: 3 }, banking: { creditGrowth: 0.4 } } },
    delayedEffects: [{ id: "supplier_stabilization", label: "Supplier stabilization", delay: 1, economy: { supplyChainStress: -5, marketConfidence: 2 } }],
    frameworkTags: ["Supply Chain Frictions"],
    advisorHint: { easy: "Offsets tariff pain for autos, but adds fiscal cost.", normal: "Targeted relief can reduce second-round layoffs.", hard: "Downstream support." },
  },
  {
    id: "consumer_rebate",
    label: "Consumer rebate",
    category: "Fiscal / Industrial",
    description: "Send temporary rebates to households facing higher goods prices.",
    immediateEffects: { economy: { fiscalBalance: -0.6, debtToGdp: 0.8, approval: 4, welfare: 2, inflation: 0.15 }, sectors: { consumerGoods: { stress: -5 } } },
    delayedEffects: [{ id: "rebate_demand", label: "Rebate demand impulse", delay: 1, economy: { gdpGrowth: 0.15, inflationExpectations: 0.1 } }],
    frameworkTags: ["Political Economy", "Market Expectations"],
    advisorHint: { easy: "Popular, but can add demand-side inflation and debt.", normal: "Relief may blunt voter anger while complicating inflation control.", hard: "Fiscal transfer." },
  },
  {
    id: "infrastructure_investment",
    label: "Infrastructure investment",
    category: "Fiscal / Industrial",
    description: "Accelerate port, rail, and energy projects that raise long-run capacity.",
    immediateEffects: { economy: { fiscalBalance: -0.9, debtToGdp: 1.3, gdpGrowth: 0.15, approval: 2 }, sectors: { steel: { output: 3, stress: -3 }, autos: { stress: -2 } } },
    delayedEffects: [{ id: "capacity_boost", label: "Capacity boost", delay: 3, economy: { gdpGrowth: 0.35, supplyChainStress: -7, welfare: 4 }, sectors: { steel: { output: 4 }, agriculture: { output: 3 } } }],
    frameworkTags: ["Supply Chain Frictions", "Market Expectations"],
    advisorHint: { easy: "Good long-run capacity, but bond markets may dislike more debt.", normal: "Productive debt is still debt if credibility is weak.", hard: "Public investment." },
  },
  {
    id: "austerity_package",
    label: "Austerity package",
    category: "Fiscal / Industrial",
    description: "Cut spending to reassure bond investors and slow debt accumulation.",
    immediateEffects: { economy: { fiscalBalance: 0.8, debtToGdp: -0.6, gdpGrowth: -0.3, unemployment: 0.25, approval: -4, marketConfidence: 4 }, sectors: { consumerGoods: { stress: 4 }, banking: { stress: 2 } } },
    delayedEffects: [{ id: "fiscal_drag", label: "Fiscal drag", delay: 1, economy: { gdpGrowth: -0.15, unemployment: 0.15, inflation: -0.1 } }],
    frameworkTags: ["Market Expectations", "Political Economy"],
    advisorHint: { easy: "Improves debt optics, but hurts growth and approval.", normal: "Markets like discipline until recession risk rises.", hard: "Consolidation." },
  },
  {
    id: "hold_rate",
    label: "Hold policy rate",
    category: "Central Bank",
    description: "Keep rates unchanged and preserve optionality.",
    immediateEffects: { economy: { centralBankCredibility: 1 } },
    delayedEffects: [{ id: "steady_policy", label: "Steady monetary stance", delay: 1, economy: { inflationExpectations: -0.05 } }],
    frameworkTags: ["Central Bank Signaling"],
    advisorHint: { easy: "Safe if inflation expectations are stable; weak if inflation is accelerating.", normal: "A hold communicates patience, not indifference.", hard: "Hold." },
  },
  {
    id: "hike_rate",
    label: "Hike rate",
    category: "Central Bank",
    description: "Raise rates to lean against inflation and expectations.",
    immediateEffects: { economy: { policyRate: 0.5, inflationExpectations: -0.2, currencyIndex: 2, equityIndex: -3, bankStress: 3, approval: -1, centralBankCredibility: 2 } },
    delayedEffects: [{ id: "monetary_lag", label: "Monetary tightening lag", delay: 2, economy: { inflation: -0.25, unemployment: 0.25, gdpGrowth: -0.2 }, sectors: { banking: { stress: 4, creditGrowth: -0.3 } } }],
    frameworkTags: ["Central Bank Signaling", "Market Expectations"],
    advisorHint: { easy: "Lowers inflation expectations over time, but raises unemployment and bank stress.", normal: "Credibility improves if tightening matches inflation risk.", hard: "Tighten." },
  },
  {
    id: "cut_rate",
    label: "Cut rate",
    category: "Central Bank",
    description: "Lower rates to support growth, credit, and equity valuations.",
    immediateEffects: { economy: { policyRate: -0.5, gdpGrowth: 0.2, inflationExpectations: 0.25, currencyIndex: -3, equityIndex: 4, approval: 2, centralBankCredibility: -2 }, sectors: { banking: { creditGrowth: 0.5, stress: -2 } } },
    delayedEffects: [{ id: "easier_credit", label: "Easier credit impulse", delay: 1, economy: { inflation: 0.2, unemployment: -0.15 }, sectors: { autos: { output: 2 }, consumerGoods: { output: 2 } } }],
    frameworkTags: ["Central Bank Signaling", "Market Expectations"],
    advisorHint: { easy: "Supports growth now, but weakens currency and raises inflation expectations.", normal: "Stimulus can look inconsistent during a tariff inflation shock.", hard: "Ease." },
  },
  {
    id: "emergency_liquidity",
    label: "Emergency liquidity",
    category: "Central Bank",
    description: "Offer bank funding facilities to stop financial stress from spreading.",
    immediateEffects: { economy: { bankStress: -10, marketConfidence: 3, centralBankCredibility: -1 }, sectors: { banking: { stress: -12, creditGrowth: 0.2 } } },
    delayedEffects: [{ id: "liquidity_moral_hazard", label: "Liquidity moral hazard questions", delay: 2, economy: { centralBankCredibility: -2, inflationExpectations: 0.05 } }],
    frameworkTags: ["Central Bank Signaling", "Market Expectations"],
    advisorHint: { easy: "Useful in banking stress; overuse can look like panic or bailout policy.", normal: "Liquidity solves funding problems, not solvency or inflation.", hard: "Liquidity backstop." },
  },
  {
    id: "hawkish_guidance",
    label: "Hawkish guidance",
    category: "Central Bank",
    description: "Signal willingness to tighten if inflation expectations drift higher.",
    immediateEffects: { economy: { inflationExpectations: -0.15, bondYield: -0.05, centralBankCredibility: 1, equityIndex: -1 } },
    delayedEffects: [{ id: "guidance_test", label: "Guidance credibility test", delay: 1, economy: { inflationExpectations: -0.1 } }],
    frameworkTags: ["Central Bank Signaling", "Bayesian Updating"],
    advisorHint: { easy: "Works best when credibility is already high and policy is consistent.", normal: "Words are cheap unless future actions validate them.", hard: "Signal resolve." },
  },
  {
    id: "dovish_guidance",
    label: "Dovish guidance",
    category: "Central Bank",
    description: "Signal patience and concern for unemployment and credit conditions.",
    immediateEffects: { economy: { approval: 2, gdpGrowth: 0.1, inflationExpectations: 0.15, equityIndex: 2, centralBankCredibility: -1 } },
    delayedEffects: [{ id: "dovish_expectations", label: "Dovish expectations drift", delay: 1, economy: { inflationExpectations: 0.1, currencyIndex: -1 } }],
    frameworkTags: ["Central Bank Signaling", "Market Expectations"],
    advisorHint: { easy: "Helps approval short term, but can unanchor expectations.", normal: "Patience is costly if markets infer tolerance for inflation.", hard: "Signal patience." },
  },
];

export const policyById = Object.fromEntries(invisibleHandsPolicies.map((policy) => [policy.id, policy])) as Record<string, PolicyAction>;
