const CURRICULUM=Object.keys(DATA),NAV=[...CURRICULUM,"Finished"],TOTAL=CURRICULUM.reduce((n,k)=>n+DATA[k].length,0),FINISHED_MAP=Object.fromEntries(PERSONAL_FINISHED.map(b=>[b[0],b]));
let active=CURRICULUM[0],status={},coverCache={};try{status=JSON.parse(localStorage.getItem("ballzatram-reading-room")||"{}")}catch(e){}try{coverCache=JSON.parse(localStorage.getItem("ballzatram-cover-cache-v2")||"{}")}catch(e){}
const slug=s=>s.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,""),get=t=>status[slug(t)]||DEFAULTS[t]||(FINISHED_MAP[t]?"Read":"Unread");
function themeFor(track){return track==="Finished"?FINISHED_THEME:THEMES[track]}
function setTheme(track){const t=themeFor(track);document.documentElement.style.setProperty("--accent",t.accent);document.documentElement.style.setProperty("--accent2",t.accent2);document.documentElement.style.setProperty("--page",t.bg);document.documentElement.style.setProperty("--hero",t.hero);document.querySelector('meta[name="theme-color"]').content=t.bg;}
function save(t,s){status[slug(t)]=s;localStorage.setItem("ballzatram-reading-room",JSON.stringify(status));render()}
function finishedRows(){const seen=new Set(),out=[];PERSONAL_FINISHED.forEach(b=>{if(get(b[0])==="Read"&&!seen.has(b[0])){seen.add(b[0]);out.push(b)}});CURRICULUM.forEach(k=>DATA[k].forEach(b=>{if(get(b[0])==="Read"&&!seen.has(b[0])){seen.add(b[0]);out.push(b)}}));return out}
function stats(){let r=0,g=0;CURRICULUM.forEach(k=>DATA[k].forEach(([t])=>{const s=get(t);if(s==="Read")r++;else if(s==="Reading")g++;}));const p=Math.round((r+g*.25)/TOTAL*100);readCount.textContent=finishedRows().length;readingCount.textContent=g;totalCount.textContent=TOTAL;pct.textContent=p+"%";meter.style.width=p+"%";profile.textContent=p<10?"Curious Generalist":p<25?"Building a World Model":p<45?"Systems-Minded Reader":p<70?"Interdisciplinary Operator":p<90?"Independent Scholar":"Walking Encyclopedia";}
function tabButton(track){const b=document.createElement("button");b.className="tab"+(track===active?" active":"");b.type="button";b.dataset.track=track;b.style.setProperty("--tabAccent",themeFor(track).accent);b.innerHTML="<strong></strong><small></small>";b.querySelector("strong").textContent=track;if(track==="Finished")b.querySelector("small").textContent=finishedRows().length+" books";else b.querySelector("small").textContent=DATA[track].filter(([t])=>get(t)==="Read").length+"/30 read";return b;}
async function openLibraryCover(title,author){try{const q=new URLSearchParams({title,author,limit:"1",fields:"cover_i"});const res=await fetch("https://openlibrary.org/search.json?"+q.toString());if(!res.ok)return null;const j=await res.json(),id=j.docs&&j.docs[0]&&j.docs[0].cover_i;return id?"https://covers.openlibrary.org/b/id/"+id+"-L.jpg":null}catch(e){return null}}
async function googleCover(title,author){try{const q=encodeURIComponent('intitle:"'+title+'" inauthor:"'+author.split("&")[0].trim()+'"'),res=await fetch("https://www.googleapis.com/books/v1/volumes?q="+q+"&maxResults=1");if(!res.ok)return null;const j=await res.json(),u=j.items&&j.items[0]&&j.items[0].volumeInfo&&j.items[0].volumeInfo.imageLinks&&(j.items[0].volumeInfo.imageLinks.thumbnail||j.items[0].volumeInfo.imageLinks.smallThumbnail);return u?u.replace(/^http:/,"https:").replace("zoom=1","zoom=2"):null}catch(e){return null}}
async function hydrateCover(img,title,author){const k=slug(title+"-"+author);if(coverCache[k]){img.src=coverCache[k];return;}let url=await openLibraryCover(title,author);if(!url)url=await googleCover(title,author);if(url){coverCache[k]=url;try{localStorage.setItem("ballzatram-cover-cache-v2",JSON.stringify(coverCache))}catch(e){}img.src=url;}}
function bookCard([title,author],i){const s=get(title),article=document.createElement("article");article.className="book";const wrap=document.createElement("div");wrap.className="coverWrap";const fb=document.createElement("div");fb.className="fallback";fb.innerHTML="<div class='ft'></div><div class='fa'></div>";fb.querySelector(".ft").textContent=title;fb.querySelector(".fa").textContent=author;const img=document.createElement("img");img.className="cover";img.alt="Cover of "+title;img.loading="lazy";img.addEventListener("load",()=>img.classList.add("loaded"));img.addEventListener("error",()=>img.removeAttribute("src"));const pill=document.createElement("span");pill.className="statusPill"+(s==="Read"?" read":"");pill.textContent=s;wrap.append(fb,img,pill);const meta=document.createElement("div");meta.className="bookMeta";const h=document.createElement("h3");h.textContent=title;const a=document.createElement("div");a.className="author";a.textContent=author;const states=document.createElement("div");states.className="states";["Unread","Reading","Read"].forEach(st=>{const b=document.createElement("button");b.type="button";b.className="state"+(s===st?" on":"");b.dataset.title=title;b.dataset.state=st;b.textContent=st;states.append(b);});meta.append(h,a,states);article.append(wrap,meta);setTimeout(()=>hydrateCover(img,title,author),Math.min(i,10)*75);return article;}
function render(){setTheme(active);tabs.replaceChildren(...NAV.map(tabButton));const idx=NAV.indexOf(active),theme=themeFor(active),isFinished=active==="Finished";hero.dataset.glyph=theme.glyph;hero.querySelector(".kicker").textContent=isFinished?"Personal archive":"Shelf "+(idx+1)+" of "+CURRICULUM.length;shelfTitle.textContent=active;shelfBlurb.textContent=isFinished?FINISHED_BLURB:BLURBS[active];shelfQuote.textContent=theme.quote;const q=search.value.trim().toLowerCase(),source=isFinished?finishedRows():DATA[active],rows=source.filter(([t,a])=>(t+" "+a).toLowerCase().includes(q));grid.replaceChildren(...(rows.length?rows.map(bookCard):[Object.assign(document.createElement("div"),{className:"empty",textContent:"No books match that search."})]));if(isFinished)shelfProgress.innerHTML="<b>"+source.length+"</b> books finished";else{shelfProgress.innerHTML="<b>"+DATA[active].filter(([t])=>get(t)==="Read").length+"</b> of 30 completed"}stats();}
tabs.addEventListener("click",e=>{const b=e.target.closest("button[data-track]");if(!b)return;active=b.dataset.track;search.value="";render();b.scrollIntoView({behavior:"smooth",inline:"center",block:"nearest"});});
grid.addEventListener("click",e=>{const b=e.target.closest("button[data-state]");if(!b)return;save(b.dataset.title,b.dataset.state);});
search.addEventListener("input",render);render();