const CURRICULUM=Object.keys(DATA);
const NAV=[...CURRICULUM,"Finished"];
const TOTAL=CURRICULUM.reduce((n,k)=>n+DATA[k].length,0);
const FINISHED_MAP=Object.fromEntries(PERSONAL_FINISHED.map(b=>[b[0],b]));

const el={
  tabs:document.getElementById("tabs"),hero:document.getElementById("hero"),shelfTitle:document.getElementById("shelfTitle"),shelfBlurb:document.getElementById("shelfBlurb"),shelfQuote:document.getElementById("shelfQuote"),search:document.getElementById("search"),shelfProgress:document.getElementById("shelfProgress"),grid:document.getElementById("grid"),readCount:document.getElementById("readCount"),readingCount:document.getElementById("readingCount"),totalCount:document.getElementById("totalCount"),pct:document.getElementById("pct"),meter:document.getElementById("meter"),profile:document.getElementById("profile")
};

let active=CURRICULUM[0],status={},coverCache={};
try{status=JSON.parse(localStorage.getItem("ballzatram-reading-room")||"{}")}catch(e){}
try{coverCache=JSON.parse(localStorage.getItem("ballzatram-cover-cache-v7")||"{}")}catch(e){}
const slug=s=>s.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
const get=t=>status[slug(t)]||DEFAULTS[t]||(FINISHED_MAP[t]?"Read":"Unread");
function themeFor(track){return track==="Finished"?FINISHED_THEME:THEMES[track]}
function setTheme(track){const t=themeFor(track);document.documentElement.style.setProperty("--accent",t.accent);document.documentElement.style.setProperty("--accent2",t.accent2);document.documentElement.style.setProperty("--page",t.bg);document.documentElement.style.setProperty("--hero",t.hero);const m=document.querySelector('meta[name="theme-color"]');if(m)m.content=t.bg;}
function save(t,s){status[slug(t)]=s;try{localStorage.setItem("ballzatram-reading-room",JSON.stringify(status))}catch(e){}render()}
function finishedRows(){const seen=new Set(),out=[];PERSONAL_FINISHED.forEach(b=>{if(get(b[0])==="Read"&&!seen.has(b[0])){seen.add(b[0]);out.push(b)}});CURRICULUM.forEach(k=>DATA[k].forEach(b=>{if(get(b[0])==="Read"&&!seen.has(b[0])){seen.add(b[0]);out.push(b)}}));return out}
function updateStats(){let r=0,g=0;CURRICULUM.forEach(k=>DATA[k].forEach(([t])=>{const s=get(t);if(s==="Read")r++;else if(s==="Reading")g++}));const p=Math.round((r+g*.25)/TOTAL*100);el.readCount.textContent=finishedRows().length;el.readingCount.textContent=g;el.totalCount.textContent=TOTAL;el.pct.textContent=p+"%";el.meter.style.width=p+"%";el.profile.textContent=p<10?"Curious Generalist":p<25?"Building a World Model":p<45?"Systems-Minded Reader":p<70?"Interdisciplinary Operator":p<90?"Independent Scholar":"Walking Encyclopedia"}
function tabButton(track){const b=document.createElement("button");b.className="tab"+(track===active?" active":"");b.type="button";b.dataset.track=track;b.style.setProperty("--tabAccent",themeFor(track).accent);const strong=document.createElement("strong"),small=document.createElement("small");strong.textContent=track;small.textContent=track==="Finished"?finishedRows().length+" books":DATA[track].filter(([t])=>get(t)==="Read").length+"/30 read";b.append(strong,small);return b}
function googleJsonp(title,author){return new Promise(resolve=>{const cb="gbooks_"+Math.random().toString(36).slice(2),script=document.createElement("script");let done=false;const finish=v=>{if(done)return;done=true;clearTimeout(timer);try{delete window[cb]}catch(e){};if(script.parentNode)script.parentNode.removeChild(script);resolve(v)};const timer=setTimeout(()=>finish(null),5000);window[cb]=j=>{try{for(const item of((j&&j.items)||[])){const links=(item.volumeInfo&&item.volumeInfo.imageLinks)||{},u=links.large||links.medium||links.small||links.thumbnail||links.smallThumbnail;if(u){finish(u.replace(/^http:/,"https:").replace("zoom=1","zoom=2").replace("&edge=curl","").replace("edge=curl&",""));return}}}catch(e){}finish(null)};const q='intitle:"'+title+'" inauthor:"'+author.split("&")[0].trim()+'"';script.src="https://www.googleapis.com/books/v1/volumes?q="+encodeURIComponent(q)+"&maxResults=3&callback="+cb;script.onerror=()=>finish(null);document.head.appendChild(script)})}
async function openLibraryCover(title,author){try{const q=new URLSearchParams({title,author,limit:"3",fields:"cover_i"}),res=await fetch("https://openlibrary.org/search.json?"+q.toString());if(!res.ok)return null;const j=await res.json(),d=(j.docs||[]).find(x=>x.cover_i);return d?"https://covers.openlibrary.org/b/id/"+d.cover_i+"-L.jpg":null}catch(e){return null}}
async function resolveCover(title,author){const k=slug(title+"-"+author);if(typeof COVER_OVERRIDES!=="undefined"&&COVER_OVERRIDES[title])return COVER_OVERRIDES[title].replace("&edge=curl","").replace("edge=curl&","");if(coverCache[k])return coverCache[k];let url=await googleJsonp(title,author);if(!url)url=await openLibraryCover(title,author);if(url){coverCache[k]=url;try{localStorage.setItem("ballzatram-cover-cache-v7",JSON.stringify(coverCache))}catch(e){}}return url}
function attachCover(wrap,title,author){resolveCover(title,author).then(url=>{if(!url||!wrap.isConnected)return;wrap.style.backgroundImage='url("'+url.replace(/"/g,"%22")+'")';wrap.style.backgroundSize="cover";wrap.style.backgroundPosition="center";wrap.classList.add("has-cover")}).catch(()=>{})}
function bookCard([title,author],i){const s=get(title),article=document.createElement("article");article.className="book";const wrap=document.createElement("div");wrap.className="coverWrap";const fb=document.createElement("div");fb.className="fallback";const ft=document.createElement("div");ft.className="ft";ft.textContent=title;const fa=document.createElement("div");fa.className="fa";fa.textContent=author;fb.append(ft,fa);const pill=document.createElement("span");pill.className="statusPill"+(s==="Read"?" read":"");pill.textContent=s;wrap.append(fb,pill);const meta=document.createElement("div");meta.className="bookMeta";const h=document.createElement("h3");h.textContent=title;const a=document.createElement("div");a.className="author";a.textContent=author;const states=document.createElement("div");states.className="states";["Unread","Reading","Read"].forEach(st=>{const b=document.createElement("button");b.type="button";b.className="state"+(s===st?" on":"");b.dataset.title=title;b.dataset.state=st;b.textContent=st;states.append(b)});meta.append(h,a,states);article.append(wrap,meta);setTimeout(()=>attachCover(wrap,title,author),Math.min(i,10)*120);return article}
function render(){try{setTheme(active);el.tabs.replaceChildren(...NAV.map(tabButton));const idx=NAV.indexOf(active),theme=themeFor(active),isFinished=active==="Finished";el.hero.dataset.glyph=theme.glyph;el.hero.querySelector(".kicker").textContent=isFinished?"Personal archive":"Shelf "+(idx+1)+" of "+CURRICULUM.length;el.shelfTitle.textContent=active;el.shelfBlurb.textContent=isFinished?FINISHED_BLURB:BLURBS[active];el.shelfQuote.textContent=theme.quote;const q=el.search.value.trim().toLowerCase(),source=isFinished?finishedRows():DATA[active],rows=source.filter(([t,a])=>(t+" "+a).toLowerCase().includes(q));el.grid.replaceChildren(...(rows.length?rows.map(bookCard):[Object.assign(document.createElement("div"),{className:"empty",textContent:"No books match that search."})]));el.shelfProgress.innerHTML=isFinished?"<b>"+source.length+"</b> books finished":"<b>"+DATA[active].filter(([t])=>get(t)==="Read").length+"</b> of 30 completed";updateStats()}catch(err){console.error(err);if(el.grid)el.grid.innerHTML='<div class="empty">The library hit a loading error. Refresh once to retry.</div>'}}
el.tabs.addEventListener("click",e=>{const b=e.target.closest("button[data-track]");if(!b)return;active=b.dataset.track;el.search.value="";render()});el.grid.addEventListener("click",e=>{const b=e.target.closest("button[data-state]");if(!b)return;save(b.dataset.title,b.dataset.state)});el.search.addEventListener("input",render);render();