const LOCAL_COVERS={
  "1491": "/internal/reading-room/covers/1491.jpg",
  "1493": "/internal/reading-room/covers/1493.jpg",
  "1984": "/internal/reading-room/covers/1984.jpg",
  "Blood Meridian": "/internal/reading-room/covers/blood-meridian.jpg",
  "Empire of the Summer Moon": "/internal/reading-room/covers/empire-of-the-summer-moon.jpg",
  "The Indifferent Stars Above": "/internal/reading-room/covers/the-indifferent-stars-above.jpg",
  "Undaunted Courage": "/internal/reading-room/covers/undaunted-courage.jpg",
  "Bury My Heart at Wounded Knee": "/internal/reading-room/covers/bury-my-heart-at-wounded-knee.jpg",
  "The Heart of Everything That Is": "/internal/reading-room/covers/the-heart-of-everything-that-is.jpg",
  "Dreams of El Dorado": "/internal/reading-room/covers/dreams-of-el-dorado.jpg",
  "Cattle Kingdom": "/internal/reading-room/covers/cattle-kingdom.jpg",
  "Tombstone": "/internal/reading-room/covers/tombstone.jpg",
  "The Last Stand": "/internal/reading-room/covers/the-last-stand.jpg",
  "Blood and Thunder": "/internal/reading-room/covers/blood-and-thunder.jpg",
  "The Apache Wars": "/internal/reading-room/covers/the-apache-wars.jpg",
  "The Comanche Empire": "/internal/reading-room/covers/the-comanche-empire.jpg",
  "The Worst Hard Time": "/internal/reading-room/covers/the-worst-hard-time.jpg",
  "The Big Burn": "/internal/reading-room/covers/the-big-burn.jpg",
  "Nothing Like It in the World": "/internal/reading-room/covers/nothing-like-it-in-the-world.jpg",
  "The Oregon Trail": "/internal/reading-room/covers/the-oregon-trail.jpg",
  "The Earth Is Weeping": "/internal/reading-room/covers/the-earth-is-weeping.jpg",
  "Son of the Morning Star": "/internal/reading-room/covers/son-of-the-morning-star.jpg",
  "Doc": "/internal/reading-room/covers/doc.jpg",
  "The Last Gunfight": "/internal/reading-room/covers/the-last-gunfight.jpg",
  "The Frontier in American History": "/internal/reading-room/covers/the-frontier-in-american-history.jpg",
  "The Legacy of Conquest": "/internal/reading-room/covers/the-legacy-of-conquest.jpg",
  "Desert Solitaire": "/internal/reading-room/covers/desert-solitaire.jpg",
  "The Guns of August": "/internal/reading-room/covers/the-guns-of-august.jpg",
  "South": "/internal/reading-room/covers/south.jpg",
  "The Rise and Fall of the Third Reich": "/internal/reading-room/covers/the-rise-and-fall-of-the-third-reich.jpg",
  "Postwar": "/internal/reading-room/covers/postwar.jpg",
  "Iron Kingdom": "/internal/reading-room/covers/iron-kingdom.jpg",
  "The Crusades": "/internal/reading-room/covers/the-crusades.jpg",
  "The Sleepwalkers": "/internal/reading-room/covers/the-sleepwalkers.jpg",
  "Angle of Repose": "/internal/reading-room/covers/angle-of-repose.jpg",
  "The Silk Roads": "/internal/reading-room/covers/the-silk-roads.jpg",
  "The Black Count": "/internal/reading-room/covers/the-black-count.jpg",
  "The Warmth of Other Suns": "/internal/reading-room/covers/the-warmth-of-other-suns.jpg",
  "The Anarchy": "/internal/reading-room/covers/the-anarchy.jpg",
  "Destiny of the Republic": "/internal/reading-room/covers/destiny-of-the-republic.jpg",
  "The Great Game": "/internal/reading-room/covers/the-great-game.jpg",
  "Stalingrad": "/internal/reading-room/covers/stalingrad.jpg",
  "The Wages of Destruction": "/internal/reading-room/covers/the-wages-of-destruction.jpg",
  "The Cold War": "/internal/reading-room/covers/the-cold-war.jpg",
  "The Second World War": "/internal/reading-room/covers/the-second-world-war.jpg",
  "Genghis Khan and the Making of the Modern World": "/internal/reading-room/covers/genghis-khan-and-the-making-of-the-modern-world.jpg",
  "A Distant Mirror": "/internal/reading-room/covers/a-distant-mirror.jpg",
  "The Peloponnesian War": "/internal/reading-room/covers/the-peloponnesian-war.jpg",
  "The Pursuit of Power": "/internal/reading-room/covers/the-pursuit-of-power.jpg",
  "The Great Sea": "/internal/reading-room/covers/the-great-sea.jpg",
  "Propaganda": "/internal/reading-room/covers/propaganda.jpg",
  "The Age of Extremes": "/internal/reading-room/covers/the-age-of-extremes.jpg",
  "The Fate of Africa": "/internal/reading-room/covers/the-fate-of-africa.jpg",
  "The Power Elite": "/internal/reading-room/covers/the-power-elite.jpg",
  "Seeing Like a State": "/internal/reading-room/covers/seeing-like-a-state.jpg",
  "Why Nations Fail": "/internal/reading-room/covers/why-nations-fail.jpg",
  "Public Opinion": "/internal/reading-room/covers/public-opinion.jpg",
  "Political Order and Political Decay": "/internal/reading-room/covers/political-order-and-political-decay.jpg",
  "The Origins of Political Order": "/internal/reading-room/covers/the-origins-of-political-order.jpg",
  "The Dictator's Handbook": "/internal/reading-room/covers/the-dictator-s-handbook.jpg",
  "CHAOS": "/internal/reading-room/covers/chaos.jpg",
  "On Tyranny": "/internal/reading-room/covers/on-tyranny.jpg",
  "The Righteous Mind": "/internal/reading-room/covers/the-righteous-mind.jpg",
  "The Logic of Collective Action": "/internal/reading-room/covers/the-logic-of-collective-action.jpg",
  "The True Believer": "/internal/reading-room/covers/the-true-believer.jpg",
  "The Crowd": "/internal/reading-room/covers/the-crowd.jpg",
  "The Image": "/internal/reading-room/covers/the-image.jpg",
  "The Color of Law": "/internal/reading-room/covers/the-color-of-law.jpg",
  "Amusing Ourselves to Death": "/internal/reading-room/covers/amusing-ourselves-to-death.jpg",
  "Trust Me, I'm Lying": "/internal/reading-room/covers/trust-me-i-m-lying.jpg",
  "The Great Transformation": "/internal/reading-room/covers/the-great-transformation.jpg",
  "The Narrow Corridor": "/internal/reading-room/covers/the-narrow-corridor.jpg",
  "The Attention Merchants": "/internal/reading-room/covers/the-attention-merchants.jpg",
  "Democracy in America": "/internal/reading-room/covers/democracy-in-america.jpg",
  "The Anatomy of Fascism": "/internal/reading-room/covers/the-anatomy-of-fascism.jpg",
  "21st Century Monetary Policy": "/internal/reading-room/covers/21st-century-monetary-policy.jpg",
  "Lords of Finance": "/internal/reading-room/covers/lords-of-finance.jpg",
  "The Age of Surveillance Capitalism": "/internal/reading-room/covers/the-age-of-surveillance-capitalism.jpg",
  "This Time Is Different": "/internal/reading-room/covers/this-time-is-different.jpg",
  "The Great Crash 1929": "/internal/reading-room/covers/the-great-crash-1929.jpg",
  "The Big Short": "/internal/reading-room/covers/the-big-short.jpg",
  "When Genius Failed": "/internal/reading-room/covers/when-genius-failed.jpg",
  "Money Changes Everything": "/internal/reading-room/covers/money-changes-everything.jpg",
  "Against the Gods": "/internal/reading-room/covers/against-the-gods.jpg",
  "A Monetary History of the United States": "/internal/reading-room/covers/a-monetary-history-of-the-united-states.jpg",
  "The New Jim Crow": "/internal/reading-room/covers/the-new-jim-crow.jpg",
  "Stress Test": "/internal/reading-room/covers/stress-test.jpg",
  "Too Big to Fail": "/internal/reading-room/covers/too-big-to-fail.jpg",
  "The Alchemists": "/internal/reading-room/covers/the-alchemists.jpg",
  "Devil Take the Hindmost": "/internal/reading-room/covers/devil-take-the-hindmost.jpg",
  "The Ascent of Money": "/internal/reading-room/covers/the-ascent-of-money.jpg",
  "The Misbehavior of Markets": "/internal/reading-room/covers/the-misbehavior-of-markets.jpg",
  "Fooled by Randomness": "/internal/reading-room/covers/fooled-by-randomness.jpg",
  "The Black Swan": "/internal/reading-room/covers/the-black-swan.jpg",
  "Adaptive Markets": "/internal/reading-room/covers/adaptive-markets.jpg",
  "Expected Returns": "/internal/reading-room/covers/expected-returns.jpg",
  "Capitalism and Freedom": "/internal/reading-room/covers/capitalism-and-freedom.jpg",
  "The Most Important Thing": "/internal/reading-room/covers/the-most-important-thing.jpg",
  "More Money Than God": "/internal/reading-room/covers/more-money-than-god.jpg",
  "The Man Who Solved the Market": "/internal/reading-room/covers/the-man-who-solved-the-market.jpg",
  "Trillion Dollar Triage": "/internal/reading-room/covers/trillion-dollar-triage.jpg",
  "The Strategy of Conflict": "/internal/reading-room/covers/the-strategy-of-conflict.jpg",
  "The Deficit Myth": "/internal/reading-room/covers/the-deficit-myth.jpg",
  "The Waste Lands": "/internal/reading-room/covers/the-waste-lands.jpg",
  "Lonesome Dove": "/internal/reading-room/covers/lonesome-dove.jpg",
  "Butcher's Crossing": "/internal/reading-room/covers/butcher-s-crossing.jpg",
  "War and Peace": "/internal/reading-room/covers/war-and-peace.jpg",
  "All the King's Men": "/internal/reading-room/covers/all-the-king-s-men.jpg",
  "The Grapes of Wrath": "/internal/reading-room/covers/the-grapes-of-wrath.jpg",
  "For Whom the Bell Tolls": "/internal/reading-room/covers/for-whom-the-bell-tolls.jpg",
  "Shōgun": "/internal/reading-room/covers/sho-gun.jpg",
  "The Count of Monte Cristo": "/internal/reading-room/covers/the-count-of-monte-cristo.jpg",
  "East of Eden": "/internal/reading-room/covers/east-of-eden.jpg",
  "No Country for Old Men": "/internal/reading-room/covers/no-country-for-old-men.jpg",
  "True Grit": "/internal/reading-room/covers/true-grit.jpg",
  "The Son": "/internal/reading-room/covers/the-son.jpg",
  "News of the World": "/internal/reading-room/covers/news-of-the-world.jpg",
  "The Killer Angels": "/internal/reading-room/covers/the-killer-angels.jpg",
  "A Gentleman in Moscow": "/internal/reading-room/covers/a-gentleman-in-moscow.jpg",
  "The Pillars of the Earth": "/internal/reading-room/covers/the-pillars-of-the-earth.jpg",
  "I, Claudius": "/internal/reading-room/covers/i-claudius.jpg",
  "Wolf Hall": "/internal/reading-room/covers/wolf-hall.jpg",
  "The Name of the Rose": "/internal/reading-room/covers/the-name-of-the-rose.jpg",
  "The Things They Carried": "/internal/reading-room/covers/the-things-they-carried.jpg",
  "Catch-22": "/internal/reading-room/covers/catch-22.jpg",
  "Brave New World": "/internal/reading-room/covers/brave-new-world.jpg",
  "One Hundred Years of Solitude": "/internal/reading-room/covers/one-hundred-years-of-solitude.jpg",
  "The Brothers Karamazov": "/internal/reading-room/covers/the-brothers-karamazov.jpg",
  "The Remains of the Day": "/internal/reading-room/covers/the-remains-of-the-day.jpg",
  "The Hundred-Page Machine Learning Book": "/internal/reading-room/covers/the-hundred-page-machine-learning-book.jpg",
  "Hands-On Machine Learning with Scikit-Learn, Keras & TensorFlow": "/internal/reading-room/covers/hands-on-machine-learning-with-scikit-learn-keras-tensorflow.jpg",
  "Deep Learning": "/internal/reading-room/covers/deep-learning.jpg",
  "Designing Machine Learning Systems": "/internal/reading-room/covers/designing-machine-learning-systems.jpg",
  "AI Engineering": "/internal/reading-room/covers/ai-engineering.jpg",
  "Build a Large Language Model (From Scratch)": "/internal/reading-room/covers/build-a-large-language-model-from-scratch.jpg",
  "Natural Language Processing with Transformers": "/internal/reading-room/covers/natural-language-processing-with-transformers.jpg",
  "Speech and Language Processing": "/internal/reading-room/covers/speech-and-language-processing.jpg",
  "The Border Trilogy": "/internal/reading-room/covers/the-border-trilogy.jpg",
  "The Sisters Brothers": "/internal/reading-room/covers/the-sisters-brothers.jpg",
  "Pattern Recognition and Machine Learning": "/internal/reading-room/covers/pattern-recognition-and-machine-learning.jpg",
  "The Alignment Problem": "/internal/reading-room/covers/the-alignment-problem.jpg",
  "Human Compatible": "/internal/reading-room/covers/human-compatible.jpg",
  "The Coming Wave": "/internal/reading-room/covers/the-coming-wave.jpg",
  "The Innovators": "/internal/reading-room/covers/the-innovators.jpg",
  "The Dream Machine": "/internal/reading-room/covers/the-dream-machine.jpg",
  "Where Wizards Stay Up Late": "/internal/reading-room/covers/where-wizards-stay-up-late.jpg",
  "Code": "/internal/reading-room/covers/code.jpg",
  "Computer Systems: A Programmer's Perspective": "/internal/reading-room/covers/computer-systems-a-programmer-s-perspective.jpg",
  "Designing Data-Intensive Applications": "/internal/reading-room/covers/designing-data-intensive-applications.jpg",
  "The Pragmatic Programmer": "/internal/reading-room/covers/the-pragmatic-programmer.jpg",
  "Clean Architecture": "/internal/reading-room/covers/clean-architecture.jpg",
  "Don't Make Me Think": "/internal/reading-room/covers/don-t-make-me-think.jpg",
  "The Gamification of Learning and Instruction": "/internal/reading-room/covers/the-gamification-of-learning-and-instruction.jpg",
  "The Gunslinger": "/internal/reading-room/covers/the-gunslinger.jpg",
  "Fingerprints of the Gods": "/internal/reading-room/covers/fingerprints-of-the-gods.jpg",
  "Smart Money": "/internal/reading-room/covers/smart-money.jpg",
  "An Unquiet Mind": "/internal/reading-room/covers/an-unquiet-mind.jpg",
  "Never Split the Difference": "/internal/reading-room/covers/never-split-the-difference.jpg",
  "The Millionaire Next Door": "/internal/reading-room/covers/the-millionaire-next-door.jpg",
  "It": "/internal/reading-room/covers/it.jpg",
  "Animal Farm": "/internal/reading-room/covers/animal-farm.jpg",
  "Doctor Zhivago": "/internal/reading-room/covers/doctor-zhivago.jpg",
  "Of Mice and Men": "/internal/reading-room/covers/of-mice-and-men.jpg",
  "The Hobbit": "/internal/reading-room/covers/the-hobbit.jpg",
  "The Godfather": "/internal/reading-room/covers/the-godfather.jpg",
  "Ulysses": "/internal/reading-room/covers/ulysses.jpg",
  "The Art of War": "/internal/reading-room/covers/the-art-of-war.jpg",
  "Den of Thieves": "/internal/reading-room/covers/den-of-thieves.jpg",
  "A Random Walk Down Wall Street": "/internal/reading-room/covers/a-random-walk-down-wall-street.jpg",
  "Noise": "/internal/reading-room/covers/noise.jpg",
  "Economic Growth of the United States, 1790–1860": "/internal/reading-room/covers/economic-growth-of-the-united-states-1790-1860.jpg",
  "The Lord of the Rings": "/internal/reading-room/covers/the-lord-of-the-rings.jpg",
  "The Drawing of the Three": "/internal/reading-room/covers/the-drawing-of-the-three.jpg"
};
