import {safeUrl} from './core.mjs';
export const escape = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const sourceLink = (url,label) => safeUrl(url) ? `<a href="${escape(safeUrl(url))}" target="_blank" rel="noopener noreferrer">${escape(label)} ↗</a>` : escape(label);
export const dateLabel = value => value && Number.isFinite(Date.parse(value)) ? new Date(value).toLocaleString(undefined,{dateStyle:'medium',timeStyle:'short'}) : 'Not recorded';
export function recordLabel(dossier, origin) {
  if (dossier?.mode === 'demo') return 'Synthetic example · not real events';
  if (origin === 'imported') return 'Imported file · sources not verified here';
  if (origin === 'saved') return 'Saved snapshot · may be out of date';
  if (origin === 'historical') return 'Historical example · real 2022 records';
  return 'Official source record';
}
export function routeFor(tab, dossier, origin) {
  if (['tracker','guide','saved'].includes(tab) || !dossier) return `#${tab}`;
  if (dossier.tracker && origin === 'live') return `#${new URLSearchParams({bill:dossier.tracker.billId,view:tab})}`;
  if (origin === 'historical') return `#${new URLSearchParams({example:'speak-out-act',view:tab})}`;
  return `#${tab}`;
}
const views = new Set(['overview','bill','versions','congress','promises','coverage','dossier']);
export function readRoute(hash) {
  const raw=hash.replace(/^#/,''), params=new URLSearchParams(raw);
  const view=views.has(params.get('view'))?params.get('view'):'overview';
  if(params.has('bill')) return /^\d{3}-(hr|s)-[1-9]\d{0,4}$/.test(params.get('bill')) ? {bill:params.get('bill'),tab:view} : {tab:'tracker',invalid:true};
  if(params.get('example')==='speak-out-act')return {example:true,tab:view};
  return {tab:['tracker','guide','saved',...views].includes(raw)?raw:'tracker'};
}
export function overviewHTML(d, bill, research, origin) {
  const e=escape, latest=bill?.latestAction || d.tracker?.latestAction || d.actions.at(-1);
  const status=d.sources.find(s=>s.id==='status') || d.sources[0];
  const real=origin==='live' || origin==='historical';
  const evidence=(label,text)=>`<button data-evidence="${e(status.id)}" data-locator="${e(text)}">${label} ↗</button>`;
  return `<div class="view-head"><div><p class="eyebrow">THE BILL AT A GLANCE</p><h2>Start with what we can verify.</h2><p>The title is the bill’s official title. It is not an independent assessment of what the bill achieves.</p></div></div>
  <div class="overview-grid"><article class="card lead-record"><span class="badge">${e(recordLabel(d,origin))}</span><h3>${e(bill?.status || d.tracker?.status || (d.publicLaws.length?'Became law':'See the action record'))}</h3><p class="eyebrow">LATEST RECORDED ACTIVITY · ${e(latest?.date || 'Date unavailable')}</p><p class="latest-action">${e(latest?.text || 'No action recorded in this file.')}</p><div class="card-actions">${sourceLink(status.url,real?'Read the government record':'Open supplied source link')}<button data-tab="congress">See full timeline →</button></div></article>
  <article class="card"><p class="eyebrow">WHO INTRODUCED IT?</p>${d.sponsors.map(s=>`<h3>${e(s.name)}</h3><p>Formal sponsor · ${e(s.id)}</p>`).join('') || '<h3>Sponsor unavailable</h3>'}<p>Sponsorship documents who introduced the bill. It does not establish who drafted every provision or how other members voted.</p>${evidence('Inspect sponsor source','bill/sponsors')}</article></div>
  <section class="next-steps" aria-label="Explore this bill"><h3>Follow the evidence</h3><div class="journey-grid"><button data-tab="bill"><span class="step-number">01</span><strong>What does it say?</strong><span>${d.versions.length?'Read the original text and available versions.':'Text is unavailable here. See the source links.'}</span></button><button data-tab="congress"><span class="step-number">02</span><strong>Who took action?</strong><span>${d.rollcall?'Inspect the timeline and recorded House votes.':'Inspect the sponsor and the legislative timeline.'}</span></button><button data-tab="promises"><span class="step-number">03</span><strong>Did the words match?</strong><span>Build your own sourced promise comparison.</span></button></div></section>
  <section class="evidence-availability"><h3>What this page can—and cannot—show</h3><dl><div><dt>Bill text</dt><dd>${d.versions.length?`${d.versions.length} version${d.versions.length===1?'':'s'} available to read. Original documents are linked.`:'Unavailable here. This does not mean the bill has no text.'}</dd></div><div><dt>Individual votes</dt><dd>${d.rollcall?`One House roll call with ${d.rollcall.members.length} member records. This is not every vote on the bill.`:'Not collected for this bill. A chamber action is not an individual voting record.'}</dd></div><div><dt>Promise comparisons</dt><dd>${research.promises.length?`${research.promises.length} of your draft comparisons. Not independently reviewed.`:'No sourced comparisons supplied. No member has been rated.'}</dd></div><div><dt>Real-world delivery</dt><dd>Not measured here. Passage, signature, implementation, and a promised outcome are separate events.</dd></div></dl></section>
  <details class="method-details"><summary>Where the information comes from</summary><p>${real?'Bill status and text are retrieved from the U.S. Government Publishing Office. The labels above describe the supplied records.':'This file is local or imported. Its source claims have not been reverified against the published catalogue.'}</p><p>Record retrieved: ${e(dateLabel(status.retrievedAt))}. ${bill?`Activity last checked: ${e(dateLabel(bill.activityCheckedAt||bill.checkedAt))}.`:''}</p><p>Original XML documents are retained with fingerprints. Your notes belong to this snapshot. ${sourceLink(status.url,'Check the source yourself')}</p><button data-tab="guide">Read the transparency guide →</button></details>`;
}
export function guideHTML(catalogue) {
  return `<div class="view-head"><div><p class="eyebrow">A CITIZEN’S GUIDE</p><h1>Accountability starts<br>with a paper trail.</h1><p>Test public statements against documented actions and outcomes. A gap is a question to investigate, not proof of deception.</p></div></div>
  <div class="journey-grid guide-steps"><article class="card"><span class="step-number">01</span><h3>Choose a bill</h3><p>Search by title, number, topic, or sponsor. Open its overview. Use Follow to save it to this browser’s watchlist.</p><button class="primary" data-tab="tracker">Find a bill →</button></article><article class="card"><span class="step-number">02</span><h3>Check what happened</h3><p>Read the original text, compare available versions, and inspect the timeline. Use any source button to check the underlying record.</p></article><article class="card"><span class="step-number">03</span><h3>Compare words and actions</h3><p>In My comparisons, record the exact promise and its source. Explain the person’s role, supportive and contrary evidence, and the result. Your interpretation stays a draft.</p></article></div>
  <section class="evidence-availability"><h2>Know what you’re looking at</h2><dl><div><dt><span class="badge">Official source record</span></dt><dd>Automatically retrieved government bill records. A source may contain an error or lag behind events; check its date and original text.</dd></div><div><dt><span class="badge amber">Your draft</span></dt><dd>Notes, promise assessments, and headline mappings entered by you. No independent review or public rating is implied.</dd></div><div><dt><span class="badge neutral">Historical example</span></dt><dd>The Speak Out Act uses real 2022 text and House votes. Its supplied reading notes are draft interpretations. It is only opened when you choose the example.</dd></div><div><dt>Not collected / unavailable</dt><dd>A visible evidence gap. It never means zero votes, no promise, no activity, or wrongdoing.</dd></div></dl></section>
  <section class="card method-card"><h2>What runs automatically?</h2><p>The site scans GPO’s current-Congress House and Senate bill records on a four-hour schedule. While open, the tracker checks for published updates every five minutes. A failed source request keeps the last successful record and shows its age.</p><p>${catalogue?`${catalogue.bills.length.toLocaleString()} of ${catalogue.discoveredCount.toLocaleString()} discovered bills are currently searchable.`:'Coverage counts appear once the catalogue loads.'} This is a growing catalogue, not a complete or politically representative sample. Resolutions are not included. Search results are ordered by the latest recorded action, not importance or suspicion.</p><p>The site does not automatically collect campaign promises, individual roll calls for live bills, news coverage, lobbying data, or implementation outcomes. It does not assign honesty or corruption scores.</p><p>${sourceLink('https://www.govinfo.gov/bulkdata/BILLSTATUS','GPO bill-status source')} · ${sourceLink('https://www.congress.gov/','Search all legislation')}</p></section>
  <section class="grid-two guide-bottom"><article class="card"><h2>Your work belongs to you</h2><p>Watchlists and notes stay in this browser. There is no account, cross-device sync, email, or push alert. Clearing browser storage removes them. Download a research file from My notebook to keep a backup.</p><p>Optional AI assistance sends only the chosen section and question through your configured service. It is off until you set it up and ask a question.</p></article><article class="card"><h2>Independent. Open to scrutiny.</h2><p>Congressional Accountability is an independent Ballzatram project, not a government service. The same evidence standards apply to every party and member. Public records are linked so you can challenge an interpretation.</p><p>${sourceLink('https://github.com/Ballzatram/ballzatram/issues/new','Report a data or display problem')} · ${sourceLink('https://github.com/Ballzatram/ballzatram/tree/master/docs/observatory','Read the method and source code')}</p><p>Include the bill number, source link, and what looks wrong. Reports on GitHub are public; keep personal information out.</p></article></section>
  <details class="method-details"><summary>Try a historical example or restore saved research</summary><p>See how original text, version changes, and a recorded House vote fit together using the Speak Out Act (117th Congress, 2022). No fictional campaign promise is supplied.</p><button id="load-example">Open the 2022 example</button> <button id="restore-research">Import a research file</button><div id="guide-saved"></div></details>`;
}
