import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {TOPICS,STORAGE_KEY,emptyState,validateCatalog,normalizeState,loadState,saveState,importState,toggleSaved,recordAnswer,selectCards,softmax,safeURL,escapeHTML,explanation} from '../internal/reading-room/feed/core.mjs';
const data=JSON.parse(fs.readFileSync(new URL('../internal/reading-room/feed/content.json',import.meta.url),'utf8'));
const cards=data.cards;
const clone=x=>JSON.parse(JSON.stringify(x));
const storage=(initial=null)=>({value:initial,getItem(){return this.value;},setItem(key,value){assert.equal(key,STORAGE_KEY);this.value=value;}});
test('edition has 60 unique, sourced cards and three valid paths',()=>{assert.equal(validateCatalog(data),data);assert.equal(cards.length,60);assert.equal(data.paths.length,3);assert.ok(data.sources.length>=30);});
test('all five topics have material',()=>{for(const topic of Object.keys(TOPICS))assert.ok(cards.some(c=>c.topic===topic));});
test('every reference has a safe URL, scope and a check date',()=>{for(const s of data.sources){assert.ok(safeURL(s.url));assert.ok(s.scope);assert.match(s.checked,/^\d{4}-\d{2}-\d{2}$/);}});
test('catalog rejects duplicate IDs',()=>{const d=clone(data);d.cards[1].id=d.cards[0].id;assert.throws(()=>validateCatalog(d));});
test('catalog rejects unknown references',()=>{const d=clone(data);d.cards[0].sources=['not-real'];assert.throws(()=>validateCatalog(d));});
test('catalog rejects invalid quiz answers',()=>{const d=clone(data);d.cards[0].quiz.answer=999;assert.throws(()=>validateCatalog(d));});
test('catalog rejects invalid videos',()=>{const d=clone(data);d.cards[0].video='javascript:alert(1)';assert.throws(()=>validateCatalog(d));});
test('catalog rejects broken and duplicate path entries',()=>{const d=clone(data);d.paths[0].cards=['not-a-card'];assert.throws(()=>validateCatalog(d));d.paths[0].cards=[cards[0].id,cards[0].id];assert.throws(()=>validateCatalog(d));});
test('new visitors start without personal history or mastery',()=>{const s=emptyState();assert.deepEqual(s.saved,[]);assert.deepEqual(s.seen,[]);assert.deepEqual(s.answers,{});assert.equal(s.mastered,undefined);});
test('save toggles exactly one card',()=>{const s=emptyState();toggleSaved(s,cards[0].id);assert.equal(s.saved.length,1);toggleSaved(s,cards[0].id);assert.equal(s.saved.length,0);});
test('viewing is distinct from attempting a question',()=>{const s=emptyState();s.seen.push(cards[0].id);assert.equal(Object.keys(s.answers).length,0);});
test('wrong answers count as practice, not mastery',()=>{const s=emptyState(),c=cards[0];assert.equal(recordAnswer(s,c,0),false);assert.equal(s.answers[c.id].attempts,1);assert.equal(s.mastered,undefined);});
test('correct answers and retries retain the last choice',()=>{const s=emptyState(),c=cards[0];recordAnswer(s,c,0);assert.equal(recordAnswer(s,c,c.quiz.answer),true);assert.equal(s.answers[c.id].attempts,2);});
test('out-of-range attempts do not mutate state',()=>{const s=emptyState();assert.throws(()=>recordAnswer(s,cards[0],99));assert.deepEqual(s.answers,{});});
test('normalization removes unknown IDs and unexpected private fields',()=>{const s=normalizeState({version:1,saved:[cards[0].id,'unknown',cards[0].id],seen:['unknown'],answers:{},privateNotes:'must not survive',lastCard:'unknown'},cards);assert.deepEqual(s.saved,[cards[0].id]);assert.deepEqual(s.seen,[]);assert.equal(s.privateNotes,undefined);assert.equal(s.lastCard,null);});
test('normalization discards invalid answers',()=>{const raw={...emptyState(),answers:{[cards[0].id]:{choice:99,attempts:1}}};assert.deepEqual(normalizeState(raw,cards).answers,{});});
test('strict import rejects unsupported versions',()=>{assert.throws(()=>importState('{"version":2}',cards));});
test('strict import rejects malformed fields',()=>{assert.throws(()=>importState('{"version":1,"saved":"x","seen":[],"answers":{},"mix":"ai-first"}',cards));});
test('import rejects invalid JSON and oversized payloads',()=>{assert.throws(()=>importState('{',cards));assert.throws(()=>importState(' '.repeat(250001),cards));});
test('valid export round-trips without changing answers',()=>{const s=emptyState();toggleSaved(s,cards[0].id);recordAnswer(s,cards[0],1);assert.deepEqual(importState(JSON.stringify(s),cards),s);});
test('prototype-shaped import data cannot modify prototypes',()=>{const text='{"version":1,"saved":[],"seen":[],"answers":{"__proto__":{"polluted":true}},"mix":"ai-first","__proto__":{"polluted":true}}';assert.equal(importState(text,cards).polluted,undefined);assert.equal({}.polluted,undefined);});
test('corrupt storage yields a warning without overwriting',()=>{const store=storage('{');const r=loadState(store,cards);assert.ok(r.warning);assert.equal(store.value,'{');});
test('unavailable storage leaves the app usable',()=>{const store={getItem(){throw Error('Denied');},setItem(){throw Error('Quota');}};assert.ok(loadState(store,cards).warning);assert.equal(saveState(store,emptyState()),false);});
test('state persists under a separate namespace',()=>{const store=storage();assert.equal(saveState(store,emptyState()),true);assert.deepEqual(loadState(store,cards).state,emptyState());assert.notEqual(STORAGE_KEY,'ballzatram-reading-room');});
test('all cards appear once in the mixed queue',()=>{const selected=selectCards(cards,emptyState());assert.equal(selected.length,cards.length);assert.equal(new Set(selected.map(c=>c.id)).size,cards.length);});
test('AI-first begins with a transparent five-of-eight weighting',()=>{const selected=selectCards(cards,emptyState()).slice(0,8);assert.equal(selected.filter(c=>['ai','building'].includes(c.topic)).length,5);});
test('balanced mix gives each available topic a turn',()=>{const s=emptyState();s.mix='balanced';assert.deepEqual(selectCards(cards,s).slice(0,5).map(c=>c.topic),Object.keys(TOPICS));});
test('unviewed comes first within a topic, without dropping revisits',()=>{const s=emptyState();s.seen=[cards[0].id];const list=selectCards(cards,s,{topic:'ai'});assert.notEqual(list[0].id,cards[0].id);assert.equal(list.at(-1).id,cards[0].id);});
test('topic filter and search intersect',()=>{const list=selectCards(cards,emptyState(),{topic:'ai',query:'token'});assert.ok(list.length>0);assert.ok(list.every(c=>c.topic==='ai'));});
test('search is case-insensitive and trims whitespace',()=>{assert.deepEqual(selectCards(cards,emptyState(),{query:'  TOKEN  '}),selectCards(cards,emptyState(),{query:'token'}));});
test('saved queue includes only saved cards, latest first',()=>{const s=emptyState();s.saved=[cards[0].id,cards[1].id];assert.deepEqual(selectCards(cards,s,{saved:true}).map(c=>c.id),[cards[1].id,cards[0].id]);});
test('paths preserve editorial order despite viewing history',()=>{const s=emptyState(),path=data.paths[0].cards;s.seen=[path[0]];assert.deepEqual(selectCards(cards,s,{path}).map(c=>c.id),path);});
test('empty matches return safely',()=>{assert.deepEqual(selectCards(cards,emptyState(),{query:'xyz-no-such-term-927'}),[]);});
test('softmax is normalized and numerically stable',()=>{assert.deepEqual(softmax([0,0]),[0.5,0.5]);const w=softmax([10000,9999]);assert.ok(Math.abs(w.reduce((a,b)=>a+b)-1)<1e-10);assert.ok(w[0]>w[1]);});
test('softmax rejects non-finite inputs',()=>{assert.throws(()=>softmax([Infinity]));assert.throws(()=>softmax([]));});
test('external URLs refuse executable and protocol-relative inputs',()=>{for(const url of ['javascript:alert(1)','data:text/html,x','//evil.test','http://example.com','https://user:pass@example.com'])assert.equal(safeURL(url),null);});
test('HTML escaping covers injected markup and attributes',()=>{assert.equal(escapeHTML('<img x="y">&'),'&lt;img x=&quot;y&quot;&gt;&amp;');});
test('recommendation explanation does not claim a learned profile',()=>{assert.match(explanation(emptyState()),/No inferred personality/);assert.match(explanation(emptyState(),'ai'),/You selected/);});
test('HTML is unlisted, CSP-constrained and has explicit privacy copy',()=>{const html=fs.readFileSync(new URL('../internal/reading-room/feed/index.html',import.meta.url),'utf8');assert.match(html,/noindex,nofollow,noarchive/);assert.match(html,/script-src 'self'/);assert.match(html,/not an authenticated private vault/);assert.doesNotMatch(html,/assets\/frontier|assets\/win95/);});
test('app has no provider or analytics endpoint',()=>{const app=fs.readFileSync(new URL('../internal/reading-room/feed/app.mjs',import.meta.url),'utf8');assert.doesNotMatch(app,/api\.openai|api\.anthropic|google-analytics|googletagmanager|eval\(/);assert.match(app,/youtube-nocookie/);assert.match(app,/strict-origin-when-cross-origin/);assert.doesNotMatch(app,/autoplay=1/);});
