import type { Actor, GameAction, GameLayer, GameState, Scenario } from "./types";

export const baseStats: Omit<GameState, "scenarioId"|"actors"|"selectedActionIds"|"activeEvents"|"history"|"layer"> = { turn:1,inflation:55,unemployment:35,output:55,publicConfidence:50,financialStability:55,currencyStrength:50,supplyStress:50,energyPrice:55,foodPrice:50,tradeBalance:50,marketVolatility:45,policyCredibility:50,fiscalSpace:50,stabilityScore:50};

export const layers: Record<GameLayer, Actor[]> = {
 micro:["Consumers","Manufacturers","Agriculture","Energy / Oil","Commodity Markets","Banks / Credit","Labor Market","Transport / Ports"].map((n,i)=>({id:`micro-${i}`,name:n,layer:"micro",type:"node",description:`${n} node`,stress:40,stats:{throughput:50},incentives:["Best response"],respondsTo:["Inflation","Supply stress"],currentStrategy:"Watch conditions",connectedActorIds:[],conceptTags:["Expected payoff"]})),
 macro:["Central Bank","Treasury / Government","Financial Markets","Housing / Credit","Labor Market","Consumer Economy","Industrial Output","Energy System"].map((n,i)=>({id:`macro-${i}`,name:n,layer:"macro",type:"node",description:`${n} node`,stress:40,stats:{throughput:50},incentives:["Credible commitment"],respondsTo:["Policy credibility"],currentStrategy:"Assess policy",connectedActorIds:[],conceptTags:["Best response"]})),
 global:["Domestic Economy","Major Trade Partner","Oil Exporter","Food Exporter","Manufacturing Competitor","Shipping Chokepoint","Currency / FX Market","Strategic Resource Supplier"].map((n,i)=>({id:`global-${i}`,name:n,layer:"global",type:"node",description:`${n} node`,stress:45,stats:{throughput:50},incentives:["Repeated game"],respondsTo:["Tariffs"],currentStrategy:"Signal position",connectedActorIds:[],conceptTags:["Prisoner's dilemma"]}))
};

function mk(id:string,name:string,layer:GameLayer,concept:string):GameAction{return {id,name,layer,description:name,upside:"Stabilizes one channel",downside:"Creates tradeoff elsewhere",affectedStats:{},affectedActors:[],concept,conceptExplanation:`${concept} shapes this move.`}}
export const actions: GameAction[] = [
 mk("encourage-consumer-spending","Encourage Consumer Spending","micro","Expected payoff"),mk("support-agriculture-supply","Support Agriculture Supply","micro","Coordination game"),mk("subsidize-energy-inputs","Subsidize Energy Inputs","micro","Signaling"),mk("ease-credit-to-firms","Ease Credit to Firms","micro","Best response"),mk("stabilize-transport-bottlenecks","Stabilize Transport Bottlenecks","micro","Value of information"),mk("release-commodity-inventory","Release Commodity Inventory","micro","Mechanism design"),mk("wage-support-program","Wage Support Program","micro","Bargaining power"),
 mk("raise-interest-rates","Raise Interest Rates","macro","Credible commitment"),mk("cut-interest-rates","Cut Interest Rates","macro","Time inconsistency"),mk("fiscal-stimulus","Fiscal Stimulus","macro","Expected payoff"),mk("spending-cuts","Spending Cuts","macro","Backward induction"),mk("credit-tightening","Credit Tightening","macro","Dominant strategy"),mk("credit-support","Credit Support","macro","Best response"),mk("release-strategic-reserves","Release Strategic Reserves","macro","Signaling"),mk("industrial-support","Industrial Support","macro","Coordination game"),mk("forward-guidance","Forward Guidance","macro","Credible commitment"),
 mk("raise-tariffs","Raise Tariffs","global","Prisoner's dilemma"),mk("lower-tariffs","Lower Tariffs","global","Repeated game"),mk("sign-trade-deal","Sign Trade Deal","global","Bargaining power"),mk("restrict-exports","Restrict Exports","global","Dominant strategy"),mk("diversify-suppliers","Diversify Suppliers","global","Value of information"),mk("currency-defense","Currency Defense","global","Signaling"),mk("strategic-resource-purchase","Strategic Resource Purchase","global","Bayesian beliefs"),mk("negotiate-shipping-access","Negotiate Shipping Access","global","Bargaining power"),mk("retaliation-de-escalation","Retaliation De-escalation","global","Reputation")
];

export const scenarios: Scenario[] = [
 {id:"inflation-spiral",name:"Inflation Spiral",briefing:"Inflation is sticky, confidence is sliding.",objective:"Reduce inflation without deep recession.",startingState:{inflation:72,energyPrice:70,foodPrice:63,publicConfidence:42,policyCredibility:45},recommendedConcepts:["Credible commitment","Time inconsistency"],pressureProfile:{inflation:2,publicConfidence:-1,marketVolatility:1}},
 {id:"supply-shock",name:"Supply Shock",briefing:"Inputs are scarce and logistics are disrupted.",objective:"Stabilize supply chains without burning fiscal space.",startingState:{supplyStress:75,energyPrice:68,foodPrice:69,fiscalSpace:42},recommendedConcepts:["Value of information","Adverse selection"],pressureProfile:{supplyStress:2,foodPrice:1,energyPrice:1}},
 {id:"trade-war",name:"Trade War",briefing:"Tariffs are rising and retaliation threats escalate.",objective:"Protect industry while avoiding destructive retaliation.",startingState:{tradeBalance:40,currencyStrength:45,marketVolatility:58,publicConfidence:45},recommendedConcepts:["Prisoner's dilemma","Repeated game"],pressureProfile:{marketVolatility:2,tradeBalance:-1,currencyStrength:-1}}
]
