import { actions, baseStats, layers, scenarios } from "./data";
import type { Actor, EndState, GameEvent, GameState, Stats } from "./types";

const clamp=(n:number,min=0,max=100)=>Math.max(min,Math.min(max,n));
export const calculateStabilityScore=(s:GameState)=>clamp(100-0.8*s.inflation-0.7*s.unemployment+0.8*s.output+0.6*s.publicConfidence+0.5*s.financialStability+0.3*s.currencyStrength-0.7*s.supplyStress-0.5*s.marketVolatility+0.6*s.policyCredibility+0.3*s.fiscalSpace-Math.abs(s.tradeBalance-50));
export function initScenario(id:string):GameState{const sc=scenarios.find(s=>s.id===id)??scenarios[0]; const state={...baseStats,...sc.startingState,scenarioId:sc.id,layer:"macro" as const,selectedActionIds:[],actors:[...layers.micro,...layers.macro,...layers.global],activeEvents:[],history:[] } as GameState; state.stabilityScore=calculateStabilityScore(state); return state;}

function applyAction(s:GameState,id:string){if(id.includes("raise-interest")){s.inflation-=4;s.output-=3;s.unemployment+=2;s.policyCredibility+=4;} if(id.includes("cut-interest")){s.output+=3;s.unemployment-=2;s.inflation+=2;s.policyCredibility-=2;} if(id.includes("tariffs")){s.tradeBalance+=3;s.inflation+=2;s.marketVolatility+=3;} if(id.includes("deal")||id.includes("de-escalation")){s.marketVolatility-=3;s.tradeBalance+=2;s.publicConfidence+=2;} if(id.includes("reserves")||id.includes("inventory")){s.energyPrice-=4;s.foodPrice-=2;s.policyCredibility-=1;} if(id.includes("credit")){s.financialStability+=id.includes("tight")?-3:3; s.output += id.includes("tight")?-2:2;}}
function updateActors(s:GameState){s.actors=s.actors.map((a:Actor)=>{const stress=clamp((s.inflation+s.supplyStress+s.marketVolatility)/3 + (a.layer===s.layer?-8:0)); let strategy="Hold"; if(a.name.includes("Consumers")) strategy=s.publicConfidence<45?"Delay purchases":"Spend selectively"; if(a.name.includes("Manufacturers")) strategy=s.supplyStress>60?"Pass through costs":"Expand output"; if(a.name.includes("Central Bank")) strategy=s.inflation>60?"Tighten policy":"Stabilize expectations"; if(a.name.includes("Trade Partner")) strategy=s.marketVolatility>60?"Signal retaliation":"Seek bargaining"; return {...a,stress,currentStrategy:strategy};});}
function endState(s:GameState):EndState|undefined{if(s.turn<8)return; if(s.stabilityScore>75&&s.inflation<45) return "Soft Landing"; if(s.marketVolatility>75&&s.financialStability<35) return "Financial Crisis"; if(s.tradeBalance<30&&s.marketVolatility>70) return "Trade Breakdown"; if(s.inflation>70&&s.unemployment>60) return "Stagflation Trap"; if(s.output>70&&s.publicConfidence>70) return "Growth Boom"; if(s.publicConfidence<30) return "Political Backlash"; return "Fragile Recovery";}

const statKeys:[keyof GameState,...(keyof GameState)[]]=["inflation","unemployment","output","publicConfidence","financialStability","currencyStrength","supplyStress","energyPrice","foodPrice","tradeBalance","marketVolatility","policyCredibility","fiscalSpace"]
export function advanceTurn(state:GameState):GameState{const s:GameState=JSON.parse(JSON.stringify(state)); const scenario=scenarios.find(x=>x.id===s.scenarioId)!; const events:GameEvent[]=[]; s.selectedActionIds.forEach(id=>applyAction(s,id)); Object.entries(scenario.pressureProfile).forEach(([k,v])=>{if(typeof v==="number" && statKeys.includes(k as keyof GameState)){const key=k as keyof GameState; s[key]=((s[key] as number) + v) as never;}}); statKeys.forEach((k)=>{s[k]=clamp(s[k] as number) as never;}); updateActors(s); if(s.inflation>65) events.push({id:`e-${s.turn}-infl`,turn:s.turn,title:"Inflation pressure spreading",body:"Firms and households expect higher prices.",affectedActors:["Consumers","Manufacturers"],affectedStats:["inflation"],severity:"high",concept:"Expected payoff"}); if(s.supplyStress>65) events.push({id:`e-${s.turn}-sup`,turn:s.turn,title:"Supply bottlenecks spreading",body:"Ports and input markets are constrained.",affectedActors:["Transport / Ports"],affectedStats:["supplyStress"],severity:"medium",concept:"Coordination game"}); s.stabilityScore=calculateStabilityScore(s); s.endState=endState(s); const snap:Stats={inflation:s.inflation,unemployment:s.unemployment,output:s.output,publicConfidence:s.publicConfidence,financialStability:s.financialStability,currencyStrength:s.currencyStrength,supplyStress:s.supplyStress,energyPrice:s.energyPrice,foodPrice:s.foodPrice,tradeBalance:s.tradeBalance,marketVolatility:s.marketVolatility,policyCredibility:s.policyCredibility,fiscalSpace:s.fiscalSpace,stabilityScore:s.stabilityScore}; s.history.push({turn:s.turn,layer:s.layer,actionIds:[...s.selectedActionIds],statSnapshot:snap,eventIds:events.map(e=>e.id)}); s.activeEvents=[...events,...s.activeEvents].slice(0,12); s.selectedActionIds=[]; s.turn+=1; return s;}
export {actions,scenarios,layers};
